Илья Евдокимов
urfu-2017/markup-task-2 pull request #101
Opened 2017-10-17 09:46 UTC by maffas

2017-10-17 09:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 13:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 01:32 UTC, mokhov requested changes
Почти всё хорошо, но в 11 задаче хочется видеть что ввел валидный email сразу же, а не только после снятия фокуса

2017-10-19 01:32 UTC, mokhov commented on tasks/3.html
> +                article > div
Зачем здесь `>`?

2017-10-19 01:32 UTC, mokhov commented on tasks/17.html
> +                article input:checked ~ input:not(:checked)
Зачем нужен `article`?

2017-10-19 01:32 UTC, mokhov commented on tasks/16.html
> +                div.c1
Зачем нужен ли `div`?

2017-10-19 06:52 UTC, maffas commented on tasks/17.html
> +                article input:checked ~ input:not(:checked)
правы, не нужен

2017-10-19 06:55 UTC, maffas commented on tasks/3.html
> +                article > div
по заданию, он не должен выделять вложенные элементы. Поэтому я выбираю только для прямых потомков.

2017-10-19 07:00 UTC, maffas commented on tasks/16.html
> +                div.c1
если честно, я сам задавался вопросом, зачем он здесь, но без него не работает. Либо же нужно как и в случае с "c7" прописывать "!important".

2017-10-19 07:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-21 07:43 UTC, mokhov commented
Молодец 👍

2017-10-21 07:43 UTC, closed without merging