20 tasks done
urfu-2017/markup-task-2 pull request #102
Opened 2017-10-17 10:34 UTC by RomanDengin

2017-10-17 10:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 10:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 11:46 UTC, savichev-igor requested changes
Местами неплохо

Также обрати внимание на визуальную составляющую: местами не работает жёлтый цвет

:tomato:

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/1.html
> +                    aside
Можно объединить с предыдущим стилем

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/10.html
> +        <meta charset="utf8">
В предыдущем файле было с дефисом

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/10.html
> +                p.title:first-letter
Селектор тэга лишний

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/10.html
> +                p.description::first-line
Аналогично

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/10.html
> +                p.title:first-letter
И все псевдоэлементы писать через `::` желательно, ниже ты это учёл

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/12.html
> +                article > div
Очень сложно решил задание

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/13.html
> +                div:nth-of-type(4n+1) div:first-child
Сложно

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/15.html
> +                a[href$='.zip']:after
А если будет сайт с доменом `.zip`?

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/16.html
> +                div.c1
Где-то селектор тэга явно лишний

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/17.html
> +                input:nth-child(n+6):not(:checked)
Сложно

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/3.html
> +                div
Слишком обще

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/4.html
> +                article > article
Я бы сделал через `+`

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/5.html
> +                input
Грасиас

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/5.html
> +                input:checked ~ div.tab
`div` можно опустить

2017-10-17 11:46 UTC, Savichev-Igor commented on tasks/7.html
> +                .global-scope img:not([alt*='css'])
Сложно

2017-10-23 11:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 11:57 UTC, RomanDengin commented
🍏
Поправил все замечания, кроме:
* task4 - с плюсом не сработало
* task15 - понял, что имеется в виду, не понял как понять, что это сайт

2017-10-24 08:09 UTC, savichev-igor approved these changes

2017-10-24 08:09 UTC, savichev-igor commented on tasks/12.html
> +                div:nth-child(odd)
`:empty` не пробовал использовать здесь?

2017-10-24 08:09 UTC, savichev-igor commented on tasks/13.html
> +                div div:only-of-type
`div` можно опустить первый здесь

2017-10-24 08:09 UTC, savichev-igor commented on tasks/17.html
> +                :checked ~ input
Я бы всегда псевдоклассы относил или к тэгам или к классам, а не просто в воздух

2017-10-24 08:09 UTC, savichev-igor commented on tasks/17.html
> +                :checked ~ input
```
input:checked ~ input:not(:checked)
{
    outline: 1px solid #ff6698;
}
```

2017-10-24 08:09 UTC, savichev-igor commented on tasks/4.html
> +                article > article
А не работает, потому что в случае с `+`, нужно делать:
```
article + article
{
    border-top: 1px solid #000;
}
```

2017-10-24 08:09 UTC, savichev-igor commented on tasks/6.html
> +                a:link
```
a[href*='yandex']
{
    color: #ff6698;
}

a[href*='vk']
{
    color: #6698ff;
}
```

2017-10-24 08:09 UTC, savichev-igor commented on tasks/8.html
> +                a[href^='/']:not([href*='//']),
Всё решение:
```
a[href^='//']:not([href*='my-site.ru']),
a[href^='http://']:not([href*='my-site.ru']),
a[href^='https://']:not([href*='my-site.ru'])
{
    color: #ff6698;
}
```

2017-10-24 08:09 UTC, Savichev-Igor commented on tasks/15.html
> +                a[href$='.zip']::after
Добавить ещё можно [download]

2017-10-24 08:10 UTC, closed without merging

2017-10-24 08:49 UTC, RomanDengin commented on tasks/17.html
> +                :checked ~ input
ок, понял, учту

2017-10-24 08:52 UTC, RomanDengin commented on tasks/15.html
> +                a[href$='.zip']::after
хм... Не обратил внимание, спасибо

2017-10-24 08:55 UTC, RomanDengin commented
А что на счёт звёздочки? Я же сделал 20 задание.

2017-10-25 08:55 UTC, Savichev-Igor commented
Звёздочка в этом задании ставится на усмотрение ментора в зависимости от изящности и лаконичности решения, а ещё на какой итерации оно было достигнуто и как много было ошибок в первой итерации

2017-10-25 20:47 UTC, RomanDengin commented
А, ок, спасибо