Balakin Vladislav
urfu-2017/markup-task-2 pull request #105
Opened 2017-10-17 17:42 UTC by BalakinVladislav

2017-10-17 17:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 17:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 17:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-28 06:06 UTC, BalakinVladislav commented
@v3new

2017-10-29 22:28 UTC, v3new requested changes
Необходимо как минимум исправить задачи с томатом 🍅

2017-10-29 22:28 UTC, v3new commented on tasks/11.html
> +                input:not(:valid)
есть такой псевдокласс: `invalid`

2017-10-29 22:28 UTC, v3new commented on tasks/13.html
> +                div div:first-of-type:last-of-type
Повышение специфичности тут лишнее и обрати внимание на `:only-of-type`

2017-10-29 22:28 UTC, v3new commented on tasks/16.html
> +                div.c1
Тут вполне и без `div` можно обойтись

2017-10-29 22:28 UTC, v3new commented on tasks/17.html
> +                article input:checked ~ input
Выделенный инпут не должен обводиться 🍅  и повышение специфичности тут излишне

2017-10-29 22:28 UTC, v3new commented on tasks/18.html
> +                article div
Задача целиком не работает, попробуй поменять порядок CSS правил 🍅

2017-10-29 22:28 UTC, v3new commented on tasks/20.html
> +                div div:only-child,
👍

2017-10-29 22:28 UTC, v3new commented on tasks/4.html
> +                article article:not(:first-of-type)
Обрати внимание на селектор `+`

2017-10-29 22:28 UTC, v3new commented on tasks/6.html
> +                [href*='syandex']
Описка

2017-10-29 22:28 UTC, v3new commented on tasks/7.html
> +                div img:not([alt])
👍

2017-10-29 22:28 UTC, v3new commented on tasks/9.html
> +                article a[href]:link
Повышение специфичности везде лишнее

2017-10-29 22:28 UTC, v3new commented
Я поздно приступил к проверке задания, попрошу, чтобы за это не снижали балл

2017-10-31 11:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 11:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-31 11:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-31 11:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-09 06:48 UTC, v3new commented on .stylelintrc.json
> +}
Настрой редактор на добавление пустой строки в конце файла

2017-11-09 06:49 UTC, closed without merging