Александр Сатов
urfu-2017/markup-task-2 pull request #13
Opened 2017-10-11 13:34 UTC by alexSatov

2017-10-11 13:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 12:33 UTC, dotokoto requested changes
Привет! Меня зовут Наталья, я буду проверять твои задачи по верстке.

Посмотри и поправь замечания, пожалуйста. Особенно обрати внимание на избыточность селекторов во многих местах.
Если будут вопросы, обращайся )

2017-10-13 12:33 UTC, dotokoto commented on tasks/1.html
> +                    div:nth-child(3)
В этом задании можно было использовать и селектор по id

2017-10-13 12:33 UTC, dotokoto commented on tasks/2.html
> +                div.c2
Зачем в начале добавлять `div`?

2017-10-13 12:33 UTC, dotokoto commented on tasks/5.html
> +                input:checked ~ div.tab
Здесь тоже можно обойтись без `div`
Чем короче селектор и чем меньше элементов он выбирает, тем быстрее отработает. Лучше писать минимально подходящие под условия

2017-10-13 12:33 UTC, dotokoto commented on tasks/6.html
> +                a[href*='yandex.ru']
А цвет ссылки на vk не совпадает с эталонной картинкой

2017-10-13 12:33 UTC, dotokoto commented on tasks/7.html
> +                    opacity: .4;
Суть правильная, но эталонная картинка таки более прозрачная
![css 2000 2017-10-13 16-08-06](https://user-images.githubusercontent.com/8973726/31543696-d032c4c8-b030-11e7-9a40-6f447ca3bdb4.png)

2017-10-13 12:33 UTC, dotokoto commented on tasks/8.html
> +                a[target='_blank']
Это работает, но по условию нужно было выделить внешние к `my-site.ru` ресурсы. Попробуй написать селектор, опираясь именно на это условие, а не на таргеты

2017-10-13 12:33 UTC, Dotokoto commented on tasks/9.html
> +                a.link:not([href])
Можно было в предыдущих матчится на ссылку с `href`,  тогда не пришлось бы переопределять цвет

2017-10-13 12:33 UTC, Dotokoto commented on tasks/11.html
> +                input[type='email']
есть специальные псевдоклассы `:valid` и `:invalid`, которые больше подойдут для решения этой задачи

2017-10-13 12:33 UTC, Dotokoto commented on tasks/13.html
> +                div:nth-of-type(4n-3) div
Селектор получился сложный, можно упростить. Тебе нужно покрасить див, и красить нужно только тогда, когда в блоке этот див единственный. Поищи селектор, который выразит это условие

2017-10-13 12:33 UTC, Dotokoto commented on tasks/14.html
> +                    list-style-type: none;
Это условие лишнее, изначально буллеты у списка уже были спрятаны

2017-10-13 12:33 UTC, Dotokoto commented on tasks/16.html
> +                    background: #ff6698 !important;
important нужен не во всех селекторах. Попробуй обойтись без него везде, где сможешь

2017-10-13 12:33 UTC, Dotokoto commented on tasks/17.html
> +                    outline: 1px solid #ff6698;
Работает неправильно, у второго чекнутого чекбокса тоже появляется красная рамка, а не должна
![css 2000 2017-10-13 17-21-10](https://user-images.githubusercontent.com/8973726/31545997-f88b1894-b03a-11e7-8966-1c3b5c688fb8.png)

2017-10-13 12:33 UTC, Dotokoto commented on tasks/18.html
> +                    opacity: 1;
Тоже работает неправильно
![css 2000 2017-10-13 17-22-48](https://user-images.githubusercontent.com/8973726/31546055-332e86d4-b03b-11e7-997b-76e3b9dcfbe8.png)

2017-10-13 12:33 UTC, Dotokoto commented on tasks/20.html
> +                div.red-gt2:nth-child(n+3) > div
Работает так как надо, но по логике немного не то )
Надо выделить те, где количество внутренних элементов больше двух. А ты просто взял два последних больших квадрата. 
Хотелось бы, чтобы при добавлении дополнительных `div`  внутрь других квадратов тоже правильно подкрашивалось:
![css 2000 2017-10-13 17-31-52](https://user-images.githubusercontent.com/8973726/31546365-74303f14-b03c-11e7-9372-5ad6fbc155f8.png)

2017-10-13 13:35 UTC, Dotokoto commented
:tomato:

2017-10-15 08:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 08:12 UTC, dotokoto approved these changes
Проверила еще раз. Основную часть принимаю ) А дополнительное задание можно сделать еще лучше. Если будешь еще доделывать доп, то пока PR не закрываю

2017-10-16 08:12 UTC, Dotokoto commented on tasks/20.html
> +                    background: #fff;
Можно сделать эту задачу и без переопределения цвета обратно на белый, только с заданием  `background: #ff6698`. Посмотри в сторону селектора `:nth-last-child` и попробуй с помощью него задать подходящие условия

2017-10-16 09:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 10:41 UTC, Dotokoto commented on tasks/20.html
> +                .red-gt2 div:nth-last-of-type(n+3) ~ div
👍

2017-10-16 10:42 UTC, Dotokoto commented
Принята задача и доп. задание

2017-10-16 10:42 UTC, closed without merging