Водяный Михаил
urfu-2017/markup-task-2 pull request #14
Opened 2017-10-11 17:45 UTC by CoderLiQ

2017-10-11 17:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-12 08:08 UTC, nex2hex reviewed
del

2017-10-12 08:08 UTC, nex2hex commented on tasks/2.html
> +                .c1
если есть возможность использовать только селекторы по css классам, то лучше использовать только их:
1) глобальный div селектор - плохо. При добавлении нового элемента без селекторов к нему применятся стили, что неочевидно. Другое дело если у него будет указан класс `<div class="c1">` - здесь мы явно задаем желаемое поведение
2) [class='c2'] - тоже плохо. При добавлении нового класса к элементу с `c2` у него сбросятся стили из `c2`, что тоже не очевидно

Подумай, как сделать задачу используя только селекторы по классам

2017-10-12 08:08 UTC, nex2hex commented on tasks/3.html
> +                article > div
Если у элемента `<article>` указан класс, лучше использовать его - это сделает селектор не глобальным (в данном примере это не критично, просто на будущее)

2017-10-12 08:08 UTC, nex2hex commented on tasks/4.html
> +                article article:not(:nth-of-type(1))
Можно написать гораздо более простой селектор
Тут есть примеры https://www.w3schools.com/cssref/css_selectors.asp

2017-10-12 08:08 UTC, nex2hex commented on tasks/6.html
> +                article a:not(:first-child)
Если первой ссылкой поставить яндекс, код сломается
Сделай так, чтобы ссылка на vk была голубой (она может находится в любом месте иерархии), а на яндекс - красной

2017-10-12 08:08 UTC, nex2hex commented on tasks/7.html
> +                div:nth-of-type(2),
та же проблема, что и выше - поменяем порядок - все сломается. По возможности, надо этого избегать.
Обрати внимание на атрибут `alt `

2017-10-12 08:08 UTC, nex2hex commented on tasks/9.html
> +                article a[href]:hover
когда наводишь на `<a class="link" href="https://ya.ru">link</a>`, псевдоссылка не должна при этом менять цвет. Это отдельный элемент со своим поведением

2017-10-12 08:08 UTC, nex2hex commented on tasks/10.html
> +                .description:first-line
Править не обязательно, просто на будущее:

https://developer.mozilla.org/en-US/docs/Web/CSS/::first-line
CSS3 introduced the ::first-line notation (with two colons) to distinguish pseudo-classes from pseudo-elements. Browsers also accept :first-line, introduced in CSS2.

2017-10-12 13:07 UTC, nex2hex commented on tasks/12.html
> +                article div:nth-last-of-type(odd)
`nth-*` очень не гибкие конструкции
можно сделать без нее

2017-10-12 13:07 UTC, nex2hex commented on tasks/13.html
> +                article > div:nth-child(4n+1) div
аналогично, можно избавиться от nth-*

2017-10-12 13:07 UTC, nex2hex commented on tasks/14.html
> +                li:before
::

2017-10-12 13:07 UTC, nex2hex commented on tasks/15.html
> +                a[href$='.zip']:after
::

2017-10-12 13:07 UTC, nex2hex commented on tasks/15.html
> +                a[href$='.zip']:after
обрати внимание на атрибут download

2017-10-12 13:07 UTC, nex2hex commented on tasks/16.html
> +                .global-results article .c1
article не обязателен

2017-10-12 13:07 UTC, nex2hex commented on tasks/16.html
> +                .global-results article div
глобальный селеткор на div очень не спецефичен
можно обойтись без него

2017-10-12 13:07 UTC, nex2hex commented on tasks/17.html
> +                :checked ~ input
можно сделать без ресета свойства в `input:checked`

2017-10-12 13:07 UTC, nex2hex commented on tasks/18.html
> +                div
при наведении на квадрат - он должен становиться ярче
Сейчас он у тебя перекрывается article с `opacity: 0.5;`

2017-10-12 13:08 UTC, nex2hex commented
исправления лучше вносить отдельным коммитом (а не править предыдущий) - так их легче проверять

2017-10-12 15:19 UTC, nex2hex commented
@CoderLiQ :tomato:

2017-10-12 17:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 07:47 UTC, nex2hex commented on tasks/6.html
> +                [href*='yandex']
теперь правильно
на будущее - лучше указывать тег `a` - тогда будет понятнее, к чему этот селектор относится

2017-10-13 07:49 UTC, nex2hex commented on tasks/11.html
> +                input:hover
лучше использовать `:focus`. `:hover` не сработает при навигации с клавиатуры

2017-10-13 07:54 UTC, nex2hex requested changes

2017-10-13 07:54 UTC, nex2hex commented on tasks/17.html
> +                :checked ~ input
А сейчас не сработает - https://yadi.sk/i/V9BvVQFN3NiQaP

2017-10-13 07:54 UTC, nex2hex commented
:tomato:
осталась одна правка

2017-10-13 10:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 10:05 UTC, nex2hex commented
🍏

2017-10-13 10:05 UTC, nex2hex approved these changes

2017-10-13 10:41 UTC, CoderLiQ commented
@nex2hex , лейблы (accepted, extra) должны автоматически были выставиться, а сам реквест в Closed попасть или какие дальнейшие действия должны быть?

2017-10-13 11:57 UTC, closed without merging