first version.
urfu-2017/markup-task-2 pull request #15
Opened 2017-10-11 17:58 UTC by gus1234

2017-10-11 17:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-12 07:01 UTC, vaseker requested changes
🍅

2017-10-12 07:01 UTC, vaseker commented on tasks/1.html
> +</html>
Задача решена, это так. 
Однако более выгодным кажется компактное решение с перетиранием зеленых div преобладающим цветом (синий): div,что-то еще {background: #6698ff}, выставлением цвета для #id и .c1. Получается всего 3 селектора, которые читаются однозначно, без brainfuck типа elem.class | elem elem | elem.class :pseudo.
Решение усложнено, потому что здесь не требуется повышение специфичности и можно использовать более простые и быстрые селекторы.

2017-10-12 07:01 UTC, vaseker commented on tasks/1.html
> +</html>
Также явный перебор с пустыми строками, но это на вкус и цвет. Непонятно, зачем пустые строки внутри правил, достаточно обозначить сами секции секции
```css
.whatever {
  foo: bar;
}

#ololo {
  bla: bla;
}
```

2017-10-12 07:01 UTC, vaseker commented on tasks/10.html
> +                p.title::first-letter
Вообще ок, но стоит помнить, что first-letter есть в css2, а в css2 pseudo указывается через единичный : . Так выше совместимость с браузерами. Это если повезет верстать под ie6

2017-10-12 07:01 UTC, vaseker commented on tasks/12.html
> +                article.global-scope :first-child
повышение специфичности через добавление article ни к чему

2017-10-12 07:01 UTC, vaseker commented on tasks/14.html
> +                ul
не хватает отступа от + до слова

2017-10-12 07:01 UTC, vaseker commented on tasks/15.html
> +                    content: '\2193';
тут снова нет отступа

2017-10-12 07:01 UTC, vaseker commented on tasks/16.html
> +                article.global-scope > div.c2.c3.c4.c5.c6
про селектор по id знаешь (у которого большая специфичность)? тут достаточно голого #id1 для перезаписи цвета.

```css
#id1 { background: #ffb366; }
```

2017-10-12 07:01 UTC, vaseker commented on tasks/15.html
> +                    content: '\2193';
также можно использовать utf8-символы, а не энкод

2017-10-12 07:01 UTC, vaseker commented on tasks/16.html
> +                article.global-scope > div.c2.c3.c4.c5.c6
также, как и в первой задаче, присутствует избыточное повышение специфичности при указании тега элемента там, где этого не требуется

2017-10-12 07:01 UTC, vaseker commented on tasks/17.html
> +                input:checked ~ input:not(:checked)
👍

2017-10-12 07:01 UTC, vaseker commented on tasks/18.html
> +                    opacity: 1;
👍

2017-10-12 07:01 UTC, vaseker commented on tasks/19.html
> +                    background: white;
лучше писать цвета в одном измерении: #fff

2017-10-12 07:01 UTC, vaseker commented on tasks/19.html
> +                article.global-scope > div
нормально, но article тут не нужны

2017-10-12 07:01 UTC, vaseker commented on tasks/19.html
> +                article.global-scope > div
впринципе, на странице через div определены только целевые квадраты, соответсвенно, можно и от упоминания  .global-scope избавиться

2017-10-12 07:01 UTC, vaseker commented on tasks/20.html
> +                div.red-gt2 :nth-last-child(n+3):first-child ~ div
без :first-child ничего не изменится, соответсвенно, этот псевдоселектор тут не нужен

2017-10-12 07:01 UTC, vaseker commented on tasks/3.html
> +                article.global-scope > div
article не нужен

2017-10-12 07:01 UTC, vaseker commented on tasks/3.html
> +                    <div >
![shta-babuska-01](https://user-images.githubusercontent.com/1942271/31482829-43b370ee-af43-11e7-9e79-15b0eb02d410.jpg)

2017-10-12 07:01 UTC, vaseker commented on tasks/4.html
> +                    <article >Пятый</article>
АААА, Остановись!

2017-10-12 07:01 UTC, vaseker commented on tasks/9.html
> +                [href*='ya.ru']:hover
можно дешевле: просто проверять на наличие href : a[href]

2017-10-12 07:03 UTC, vaseker commented
Итого, нужно упростить ряд селекторов и разрешить остальные релевантные замечания. В целом, решение адекватное. Жду правок.

2017-10-12 08:26 UTC, gus1234 commented on tasks/1.html
> +</html>
Вообще , у меня так и было сделано , как вы говорите. Но ваш линтер не дает задавать селекторы по ID ¯\(°_o)/¯. Та же история про миллион пустых строк, они тоже нужны линтеру.

2017-10-12 08:27 UTC, gus1234 commented on tasks/10.html
> +                p.title::first-letter
надеюсь , не повезет , но спасибо , запомню.

2017-10-12 08:33 UTC, gus1234 commented on tasks/14.html
> +                ul
не особо понимаю , про какой отступ вы говорите ..

2017-10-12 08:34 UTC, gus1234 commented on tasks/16.html
> +                article.global-scope > div.c2.c3.c4.c5.c6
Знаю, та же ситуация , как и в первой задаче. Линтер не дает задавать селекторы по ID.

2017-10-12 08:43 UTC, gus1234 commented on tasks/3.html
> +                    <div >
ахах. Я сам не знаю , что это.

2017-10-12 08:46 UTC, gus1234 commented on tasks/4.html
> +                    <article >Пятый</article>
![588c93c00eb14](https://user-images.githubusercontent.com/18513308/31487325-b2673132-af53-11e7-9888-1f458494805b.jpg)

2017-10-12 08:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-12 09:12 UTC, gus1234 commented
Done.

2017-10-12 09:56 UTC, vaseker commented
@gus1234 принял.

2017-10-12 09:56 UTC, closed without merging