done
urfu-2017/markup-task-2 pull request #17
Opened 2017-10-11 20:20 UTC by Admirallll

2017-10-11 20:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 13:03 UTC, Vittly commented on tasks/1.html
> +                    div:nth-child(3)
можно было еще `.c1 + div` - знаешь такое? Не знаешь - почитай

2017-10-16 13:11 UTC, Vittly commented on tasks/2.html
> +                }
кмк можно div не красить, обойтись правилами про комбинации c1/c2. И кода будет поменьше

2017-10-16 13:12 UTC, Vittly commented on tasks/3.html
> +                }
посмотри внимательнее на получившейся результат, кажется не все гладко

2017-10-16 13:18 UTC, Vittly commented on tasks/7.html
> +                div > img:not([alt])
интересно, тут ты конкретизировал - что `div > img`, но можно было просто `img`. А выше в подобных случаях не стеснялся писать правила для всех `div`-ов на странице. Как тут конечно лучше

2017-10-16 13:20 UTC, Vittly commented on tasks/8.html
> +                [target='_blank']
выше `*=yandex` писал без кавычек, лучше бы одинаково. И я бы написал все-таки название тега

2017-10-16 13:22 UTC, Vittly commented on tasks/9.html
> +                }
про "active" сделал только для верхней ссылки, а вторая?

2017-10-16 13:23 UTC, Vittly commented on tasks/9.html
> +                    color: #6698ff;
этого не было по умолчанию?

2017-10-16 13:23 UTC, Vittly commented on tasks/9.html
> +                    color: #6698ff;
если не было, то давай наверх утащим?

2017-10-16 13:28 UTC, Vittly commented on tasks/11.html
> +                }
выглядит многословно - можно же что-то унести в `input[type='email']`, а другое сделать как "с собачкой" или "без нее"

2017-10-16 13:28 UTC, Vittly commented on tasks/11.html
> +                }
давай тут короче напишем

2017-10-16 13:30 UTC, Vittly commented on tasks/13.html
> +                    background: #ff6698;
👍

2017-10-16 13:36 UTC, Vittly commented on tasks/16.html
> +                div.c1
хм, тут опять. Почему отличается от решения в одном из первых кейсов? Там было просто `.c1`

2017-10-16 13:36 UTC, Vittly commented on tasks/16.html
> +                div.c2.c3.c4.c5.c6:empty
а почему короче не написал?

2017-10-16 13:37 UTC, Vittly commented on tasks/16.html
> +                div.c2.c3.c4.c5.c6:empty
и зачем empty?

2017-10-16 13:49 UTC, Vittly commented
🍅 
есть вопросы

2017-10-19 09:09 UTC, Admirallll commented on tasks/1.html
> +                    div:nth-child(3)
В слаке писали, что в этом задании правильно выбрать элемент по id, чтобы научиться селектору по id, так и сделал, заигноировал правило в стилевой проверке

2017-10-19 09:09 UTC, Admirallll commented on tasks/2.html
> +                }
да, обошлось без div'a

2017-10-19 09:09 UTC, Admirallll commented on tasks/3.html
> +                }
да, точно, не заметил сразу, поправил

2017-10-19 09:13 UTC, Admirallll commented on tasks/8.html
> +                [target='_blank']
вроде выше яндекс вот так: [href*='yandex'], в ковычках, стилевая проверка вроде не пропускает без них, я уже не помню

2017-10-19 09:35 UTC, Admirallll commented on tasks/9.html
> +                }
да, не подумал, что должно быть при нажатии ещё, добавил

2017-10-19 09:36 UTC, Admirallll commented on tasks/9.html
> +                    color: #6698ff;
утащил наверх

2017-10-19 09:39 UTC, Admirallll commented on tasks/11.html
> +                }
сделал покороче

2017-10-19 09:47 UTC, Admirallll commented on tasks/8.html
> +                [target='_blank']
И название тега дописал

2017-10-19 09:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 10:00 UTC, Vittly requested changes
еще есть замечания

🍅

2017-10-19 10:00 UTC, Vittly commented on tasks/11.html
> +                input[value*='@']
посмотри на псевдокласс valid

2017-10-19 10:00 UTC, Vittly commented on tasks/20.html
> +                div > div:nth-last-child(n+3):first-child ~ div
можно сильно короче

2017-10-19 10:00 UTC, Vittly commented on tasks/4.html
> +                article:not(:first-of-type)
это слишком сложный вариант, посмотри на `+`

2017-10-19 10:03 UTC, Admirallll commented on tasks/11.html
> +                input[value*='@']
done

2017-10-19 10:10 UTC, Admirallll commented on tasks/20.html
> +                div > div:nth-last-child(n+3):first-child ~ div
да, точн

2017-10-19 10:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 11:09 UTC, Vittly commented
Молодец

2017-10-19 11:09 UTC, closed without merging