test
urfu-2017/markup-task-2 pull request #21
Opened 2017-10-11 22:14 UTC by Rolyx2

2017-10-11 22:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-11 22:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 08:58 UTC, Mokoshka requested changes
🍅

2017-10-17 08:58 UTC, Mokoshka commented on tasks/1.html
> +                    div:nth-child(3)
А зачем здесь используешь nth-child? Можно ведь проще селектор сделать

2017-10-17 08:58 UTC, Mokoshka commented on tasks/1.html
> +                    aside
Свойства у селектора div и у селектора aside совпадают, можно объединить

2017-10-17 08:58 UTC, Mokoshka commented on tasks/10.html
> +                section article p.title::first-letter
Почему нельзя было просто tilte указать?

2017-10-17 08:58 UTC, Mokoshka commented on tasks/13.html
> +            .global-scope > div:nth-child(4n+1) > :first-child
Очень сложный селектор, можно проще. Я бы посоветовала поизучать псевдокласс, возможно найдется более подходящий

2017-10-17 08:58 UTC, Mokoshka commented on tasks/16.html
> +                background: #ffb366 !important;
Здесь можно избавиться от important, использовав селектор с бОльшей специфичностью

2017-10-17 08:58 UTC, Mokoshka commented on tasks/17.html
> +            }
А сможешь написать решение задачки, использовав один селектор, а не два?

2017-10-17 08:58 UTC, Mokoshka commented on tasks/18.html
> +            }
В этом задании есть проблема: если навести курсор рядом с любым квадратиком, очень близко, но не задевая квадратик, то opacity всех квадратиков меняется. Такого быть не должно, квадратики должны становиться прозрачнее только при наведении на один из квадратиков

2017-10-17 08:58 UTC, Mokoshka commented on tasks/19.html
> +                background: white;
Лучше использовать hex-код цвета, дабы не давать браузеру возможности отображать цвет, как захочет сам браузер

2017-10-17 08:58 UTC, Mokoshka commented on tasks/2.html
> +                div:first-child
Здесь можно использовать более простой селектор

2017-10-17 08:58 UTC, Mokoshka commented on tasks/2.html
> +                div:nth-child(2n)
И здесь тоже

2017-10-17 08:58 UTC, Mokoshka commented on tasks/2.html
> +                div:nth-child(3n)
И здесь

2017-10-17 08:58 UTC, Mokoshka commented on tasks/4.html
> +            section article article:not(:first-of-type)
Выглядит страшно, можно проще. Давай переделаем этот селектор)

2017-10-17 08:58 UTC, Mokoshka commented on tasks/6.html
> +
Будет круто, если сделаешь так, чтобы все ссылки yandex были красные, а вк - синим

2017-10-17 08:58 UTC, Mokoshka commented on tasks/7.html
> +            section article div:not(:first-child):not(:last-child)
Здесь проблема будет, что если вдруг мы захотим поменять порядок прозрачных и непрозрачных или добавим еще картинок, то нам придется править селектор. Здесь можно использовать такой селектор, который решит эту проблему.
Подсказка: у прозрачных элементов есть особенность, которой можно воспользоваться

2017-10-17 08:58 UTC, Mokoshka commented on tasks/9.html
> +                    {
Где-то плачет один перфекционист

2017-10-17 08:58 UTC, Mokoshka commented on tasks/9.html
> +                a:last-child:active
Во-первых, два селектора с одинаковыми свойствами
Во-вторых, может есть способ решить задачу, не переопределяя два раза opacity у элементов? То есть указать свойство opacity: .5 только у тех элементов, которым нужно

2017-10-17 11:02 UTC, Rolyx2 commented on tasks/16.html
> +                background: #ffb366 !important;
сдавал до того как можно было id использовать

2017-10-19 06:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 06:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 09:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 09:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 12:22 UTC, Mokoshka requested changes
important уберешь и будет ок

2017-10-19 12:22 UTC, Mokoshka commented on tasks/16.html
> +                background: #ffb366 !important;
А important оставил

2017-10-19 13:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-22 12:44 UTC, closed without merging