id update
urfu-2017/markup-task-2 pull request #23
Opened 2017-10-12 08:15 UTC by Morkhod

2017-10-12 08:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-12 08:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 16:28 UTC, savichev-igor requested changes
В целом всё очень круто! 

Если поправишь все замечания поставлю даже :star:

🍅

2017-10-13 16:28 UTC, savichev-igor commented on tasks/1.html
> +                /* your styles here */
Я бы комментарии удалял, если они не несут какой-то важной смысловой нагрузки

2017-10-13 16:28 UTC, savichev-igor commented on tasks/1.html
> +                :empty
Хоть и рабочая версия, но я бы лучше использовал псевдоклассы для более сложной выборки, а здесь вполне сгодится выборка по тэгам

2017-10-13 16:28 UTC, savichev-igor commented on tasks/1.html
> +</html>
Отсутствие пустой строки пропускает линтер?

2017-10-13 16:28 UTC, savichev-igor commented on tasks/3.html
> +            div:not(:empty)
Решение опять же рабочее, но попробуй посмотреть в сторону `>`, ибо как мне кажется оно сильно проще для понимания, чем псевдоклассы)

2017-10-13 16:28 UTC, savichev-igor commented on tasks/4.html
> +            article:not(:first-of-type)
Сейчас ты используешь тэг и два псевдокласса, а сможешь сделать с использованием двух тэгов?

2017-10-13 16:28 UTC, savichev-igor commented on tasks/5.html
> +            :checked ~ div
Я бы сделал `input:checked`, а то применять псевдокласс ко всем элементам как-то не очень, хоть и понятное дело, что он применится только к `input`ам

А ещё я бы указал явно стили для нечекнутого состояния, вдруг в будущем другой разработчик случайно переопределит стили, которые ты тут используешь по умолчанию и всё сломается

2017-10-13 16:28 UTC, savichev-igor commented on tasks/6.html
> +            [href*='yandex.ru']
Опять же, понятное дело, что href только обычно у тэга `<a>`, но селекторы атрибутов я бы тоже отнёс к какому-то конкретному тэгу или классу

2017-10-13 16:28 UTC, savichev-igor commented on tasks/7.html
> +            img:not([alt])
Тут даже не придраться =)

2017-10-13 16:28 UTC, savichev-igor commented on tasks/8.html
> +            a[rel='external']
На `rel` полагаться вообще не стоит, этого атрибута может не быть для новых ссылок, поэтому рекомендую всё-таки использовать `href`

2017-10-13 16:28 UTC, savichev-igor commented on tasks/10.html
> +            p.title::first-letter
Селектор тэга тут явно лишний

2017-10-13 16:28 UTC, savichev-igor commented on tasks/10.html
> +            p.description::first-line
И здесь

2017-10-13 16:28 UTC, savichev-igor commented on tasks/11.html
> +            input:not(:valid)
Можно использовать `:invalid`

2017-10-13 16:28 UTC, savichev-igor commented on tasks/13.html
> +            div:only-of-type
:fire:

2017-10-13 16:28 UTC, savichev-igor commented on tasks/14.html
> +                margin-right: 4px;
Можешь просто добавить вместо этого пробел в `content`

2017-10-13 16:28 UTC, savichev-igor commented on tasks/15.html
> +            a[href$='.zip']::after
А что если у нас будет ссылка с другим `href`, но тоже на скачивание файла?

2017-10-13 16:28 UTC, savichev-igor commented on tasks/15.html
> +                margin-left: 4px;
Аналогично пробел можешь вставить в `content`

2017-10-13 16:28 UTC, Savichev-Igor commented on tasks/16.html
> +            div:empty
Попробуй сделать без `div` в каждом селекторе

2017-10-13 16:28 UTC, Savichev-Igor commented on tasks/17.html
> +            input:checked ~ input:not(:checked)
:fire:

2017-10-13 16:28 UTC, Savichev-Igor commented on tasks/20.html
> +            div:empty:first-child:nth-last-child(n+3) ~ div:empty
Магия слишком сильная магия)

В целом норм, но зачем здесь `:empty:first-child`?

2017-10-13 18:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-14 07:59 UTC, Savichev-Igor commented on tasks/20.html
> +            div > div:nth-last-child(n+3) ~ div
Мог использовать просто класс `red-gt2`

2017-10-14 08:04 UTC, Savichev-Igor commented
Я не могу ничего сделать с этим PR, пока в нём есть конфликты

2017-10-14 21:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 06:25 UTC, savichev-igor approved these changes

2017-10-15 06:26 UTC, closed without merging