Трубецких Евгений
urfu-2017/markup-task-2 pull request #24
Opened 2017-10-12 10:21 UTC by alidus

2017-10-12 10:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-12 10:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-12 10:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 09:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 10:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 10:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 08:18 UTC, evilj0e requested changes

2017-10-15 08:18 UTC, evilj0e commented on .stylelintrc.json
> + "rules": {
Без переопределения правил должно работать. Верни назад.

2017-10-15 08:18 UTC, evilj0e commented on tasks/11.html
> +                input[value^='invalid']
Посмотри псевдоклассы, возможно тебе что-то подойдёт для этого задания.

2017-10-15 08:18 UTC, evilj0e commented on tasks/13.html
> +                div:nth-child(4n + 1) > div
Посмотри на типы узлов.
Есть идеи как переписать правило?

2017-10-15 08:18 UTC, evilj0e commented on tasks/15.html
> +                a[href$='.zip']::after
Выдели только ссылки на скачивание, если будет просто ссылка на zip, то её выделять не нужно.

2017-10-15 08:18 UTC, evilj0e commented on tasks/16.html
> +                div
Попробуй решить задачу без импортантов

2017-10-15 08:18 UTC, evilj0e commented on tasks/17.html
> +                input:checked ~ input
А если отметить чекбокс?

2017-10-15 08:18 UTC, evilj0e commented on tasks/19.html
> +                div:first-child > div:nth-child(4)
Перепиши без связи на номер.

2017-10-15 08:18 UTC, evilj0e commented on tasks/19.html
> +                div > div
Используй псевдокласс

2017-10-15 08:18 UTC, evilj0e commented on tasks/2.html
> +                .c1:first-child
Реши без псевдокласса

2017-10-15 08:18 UTC, evilj0e commented on tasks/4.html
> +                article:nth-of-type(n + 2)
Можно решить без псевдокласса

2017-10-15 08:18 UTC, evilj0e commented on tasks/5.html
> +                input#checkbox:checked ~ .tab
Реши без id

2017-10-15 08:18 UTC, evilj0e commented on tasks/7.html
> +                div > img:not([alt*='css'])
Зачем тебе `div >`?

2017-10-15 08:18 UTC, evilj0e commented on tasks/7.html
> +                div > img:not([alt*='css'])
Упрости селектор

2017-10-15 08:18 UTC, evilj0e commented on tasks/8.html
> +                a:not([href*='my-site.ru']):not([href^='/http/'])
href="//vk.com"

2017-10-15 08:18 UTC, evilj0e commented on tasks/9.html
> +                a.link[href]:link
Зачем `:link`?

2017-10-15 08:35 UTC, evilj0e commented
🍅

2017-10-15 11:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-15 11:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-27 06:12 UTC, evilj0e approved these changes
Указал лишние классы. Посмотри ниже.
В остально сделал хорошо, молодец.

2017-10-27 06:12 UTC, evilj0e commented on tasks/1.html
> +                    div:nth-child(3)
По айди было ок

2017-10-27 06:12 UTC, evilj0e commented on tasks/15.html
> +                a[href$='.zip'][download]::after
🔥

2017-10-27 06:12 UTC, evilj0e commented on tasks/16.html
> +                .global-scope div.c2.c3.c4.c5.c6
Зачем тебе лишние классы? С .с2 было же всё хорошо)

2017-10-27 06:12 UTC, evilj0e commented on tasks/8.html
> +                a[href*='//']:not([href*='my-site.ru'])
:fire:

2017-10-27 06:12 UTC, evilj0e commented
⭐️

2017-10-27 06:12 UTC, closed without merging