first attempt
urfu-2017/markup-task-2 pull request #27
Opened 2017-10-12 16:22 UTC by graf-m-96

2017-10-12 16:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-12 16:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-14 17:19 UTC, bazhenova requested changes
Привет) Есть несколько замечаний, их нужно будет поправить. А пока 🍅

2017-10-14 17:19 UTC, bazhenova commented on tasks/1.html
> +                        background: #6698ff;
Можно объединить это правило с первым

2017-10-14 17:19 UTC, bazhenova commented on tasks/3.html
> +                div > div
А нужен ли тут `>`?

2017-10-14 17:19 UTC, bazhenova commented on tasks/4.html
> +                article.global-scope > article:nth-of-type(n+2)
В `article.global-scope` можно не указывать `article`

2017-10-14 17:19 UTC, bazhenova commented on tasks/4.html
> +                article.global-scope > article:nth-of-type(n+2)
Попробуй решить задачу без использования `nth-of-type`

2017-10-14 17:19 UTC, bazhenova commented on tasks/6.html
> +                a:not([href*='yandex.ru'])
Можно и так, а можно обойтись без использования `:not`))

2017-10-14 17:19 UTC, bazhenova commented on tasks/7.html
> +                .global-scope img:not([alt*='css'])
Попробуй в этой задаче обойтись написанием только одного свойства. Подумай, что объединяет те картинки, которые должны быть немного прозрачными?

2017-10-14 17:19 UTC, bazhenova commented on tasks/8.html
> +                a[target='_blank']
Сейчас ты выделил те, которые открываются в новом окне. А мы хотим найти внешние ссылки. Перепиши, пожалуйста

2017-10-14 17:19 UTC, bazhenova commented on tasks/12.html
> +                .global-scope > div:nth-of-type(2n + 1)
Попробуй решить эту задачу без использования `nth-of-type`

2017-10-14 17:19 UTC, bazhenova commented on tasks/13.html
> +                .global-scope > div:nth-child(4n + 1) > :first-child
Перепиши такую выборку попроще. Посмотри, чем выделенные элементы отличаются от других

2017-10-14 17:19 UTC, bazhenova commented on tasks/16.html
> +                .global-scope > div.c1
Можно не указывать `div`

2017-10-14 17:19 UTC, bazhenova commented on tasks/16.html
> +                .global-scope > div#id1
И тут

2017-10-14 17:19 UTC, bazhenova commented on tasks/16.html
> +                .global-scope > div.c7
И тут

2017-10-14 17:19 UTC, bazhenova commented on tasks/17.html
> +                    outline: none !important;
Давай попробуем обойтись без `important`))

2017-10-14 17:19 UTC, bazhenova commented on tasks/18.html
> +                article.global-scope:hover > div
Тут можно не указывать `article `. То же самое и в стилях ниже

2017-10-14 17:19 UTC, bazhenova commented on tasks/19.html
> +                    background: white;
Давай будем указывать цвета в hex

2017-10-14 17:19 UTC, bazhenova commented on tasks/19.html
> +                    background: #ffb366 !important;
Попробуй переписать так, чтобы обойтись без `!important`

2017-10-14 17:19 UTC, bazhenova commented on tasks/20.html
> +                .red-gt2:nth-child(n + 3) > div
👍

2017-10-14 17:19 UTC, bazhenova commented on .stylelintrc.json
> +}
😱

2017-10-15 11:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 11:40 UTC, graf-m-96 commented on .stylelintrc.json
> +}
во время изменения файлика со стилями что-то пошло не так😅
(кажется дело в переводе строки)

2017-10-15 11:41 UTC, graf-m-96 commented on tasks/17.html
> +                    outline: none !important;
нужно было перебить специфичность и чёт психанул)

2017-10-15 11:43 UTC, graf-m-96 commented on tasks/7.html
> +                .global-scope img:not([alt*='css'])
У них нет атрибута 'alt', да?
А :not я добавил для большей строгости, которая наверно не нужна

2017-10-15 11:45 UTC, graf-m-96 commented on tasks/8.html
> +                a[target='_blank']
Просто заметил хорошую закономерность)
Переписал на алгоритм, работающий с самой ссылкой, правда не уверен, что его невозможно обойти

2017-10-15 11:45 UTC, graf-m-96 commented
Привет)
спасибо, было много годных замечаний
вроде всё исправил

2017-10-15 17:52 UTC, bazhenova commented on tasks/7.html
> +                .global-scope img:not([alt*='css'])
> У них нет атрибута 'alt', да?

Верно)

2017-10-15 17:53 UTC, bazhenova commented on .stylelintrc.json
> +}
Да, тут он ругается на отсутствие перевода строки

2017-10-15 18:00 UTC, bazhenova approved these changes
После себя лучше не оставлять лишние комментарии, которые не несут смысловой нагрузки, а только загрязняют код. А так ты хорошо постарался, молодец!

2017-10-15 18:00 UTC, bazhenova commented on tasks/18.html
> +                    /* background: green; */
Воу. На будущее - не оставляй после себя таких комментариев)

2017-10-15 18:01 UTC, closed without merging

2017-10-15 19:27 UTC, graf-m-96 commented on tasks/18.html
> +                    /* background: green; */
окей, возьму на заметку, спасиб)