Хомич Павел
urfu-2017/markup-task-2 pull request #28
Opened 2017-10-12 16:36 UTC by paulkhomich

2017-10-12 16:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-12 17:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 13:35 UTC, dotokoto requested changes
Привет! Меня зовут Наталья, я буду смотреть твои задачи. 

Посмотри и поправь замечания, пожалуйста, и приму задачу

2017-10-13 13:35 UTC, Dotokoto commented on tasks/1.html
> +                    .c1 + div
Так работает, но в этом задании лучше использовать селектор по id. В канале в слаке написали, как обойти ограничение линтера на его использование

2017-10-13 13:35 UTC, Dotokoto commented on tasks/2.html
> +                    <div class="c1 c2">a</div>
Зачем добавил буквы? html в этой задаче не нужно менять

2017-10-13 13:35 UTC, Dotokoto commented on tasks/2.html
> +                .c1 + .c2
Сложная логика. Можно было использовать селектор `.c1.c2` для первого элемента и переопределить цвет ему. А по `.c2` и `.c1` красить остальные

2017-10-13 13:35 UTC, Dotokoto commented on tasks/4.html
> +                .global-scope article:nth-of-type(1) ~ article
А здесь можно упростить, использовав селектор `+`

2017-10-13 13:35 UTC, Dotokoto commented on tasks/5.html
> +                    color: white;
Переключение не работает, у тебя всегда черный фон и белый текст. А должно переключаться по снятию/включению чекбокса

2017-10-13 13:35 UTC, Dotokoto commented on tasks/6.html
> +                a
Можно и здесь выбирать по vk.ru, чтобы цвет следующих ссылок не переопределялся

2017-10-13 13:35 UTC, Dotokoto commented on tasks/7.html
> +                    opacity: .5;
На эталонной картинке прозрачность больше :)

2017-10-13 13:35 UTC, Dotokoto commented on tasks/11.html
> +                input:valid
👍

2017-10-13 13:35 UTC, Dotokoto commented on tasks/15.html
> +                a[href$='zip']::after
В селектор можно еще добавить проверку на `download`, так как в задаче требуется отметить именно ссылки на скачивание

2017-10-13 13:35 UTC, Dotokoto commented on tasks/16.html
> +                    background: #6698ff !important;
Здесь можно обойтись без `important`, если сделать селектор с бОльшим весом

2017-10-13 13:35 UTC, Dotokoto commented on tasks/18.html
> +                    opacity: .5;
Работает не до конца правильно. При наведении на один остальные должны становиться еще более прозрачными

2017-10-13 13:35 UTC, Dotokoto commented on tasks/19.html
> +                .global-scope > div
Зачем везде добавлен `.global-scope`? Можно обойтись без него

2017-10-13 13:35 UTC, Dotokoto commented on tasks/20.html
> +                    background: #ff6698;
👍

2017-10-13 13:35 UTC, Dotokoto commented
🍅

2017-10-13 18:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-13 18:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 19:00 UTC, pvlkhm commented
@Dotokoto Привет! Спасибо за оперативный и развернутый ответ. Все правки сделал, все уяснил

2017-10-16 08:21 UTC, dotokoto approved these changes
Принято! 👌

2017-10-16 08:21 UTC, Dotokoto commented on tasks/4.html
> +                .global-scope article:nth-of-type(n) + article
Можно было просто `article + article`, будет то же самое

2017-10-16 08:21 UTC, closed without merging