1
urfu-2017/markup-task-2 pull request #31
Opened 2017-10-12 18:36 UTC by Edheltur

2017-10-12 18:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 14:27 UTC, Vittly requested changes
🍅

2017-10-16 14:27 UTC, Vittly commented on tasks/1.html
> -                    /* your styles here */
давай все коммит-мессаджи по-русски

2017-10-16 14:27 UTC, Vittly commented on tasks/13.html
> +                div:only-of-type
а одного не хватит?

2017-10-16 14:27 UTC, Vittly commented on tasks/3.html
> +                .global-scope > div
до этого же не писал global-scope - зачем тут?

2017-10-16 14:27 UTC, Vittly commented on tasks/8.html
> +                a[href*='//']:not([href*='my-site.ru'])
есть признак проще/короче

2017-10-16 14:27 UTC, Vittly commented on tasks/18.html
> +                .global-scope > div:hover
можно просто `article`

2017-10-16 14:27 UTC, Vittly commented on tasks/20.html
> +                div.red-gt2 :nth-last-child(n+3) ~ div
можно короче

2017-10-16 18:09 UTC, Edheltur commented on tasks/1.html
> -                    /* your styles here */
🇷🇺

2017-10-16 18:09 UTC, Edheltur commented on tasks/13.html
> +                div:only-of-type
➕

2017-10-16 18:10 UTC, Edheltur commented on tasks/3.html
> +                .global-scope > div
➕

2017-10-16 18:17 UTC, Edheltur commented on tasks/3.html
> +                .global-scope > div
Убрал у одного из селекторов. Кажется без каскада все равно тут не обойтись.

2017-10-16 18:21 UTC, Edheltur commented on tasks/8.html
> +                a[href*='//']:not([href*='my-site.ru'])
➕

2017-10-16 18:24 UTC, Edheltur commented on tasks/20.html
> +                div.red-gt2 :nth-last-child(n+3) ~ div
➕

2017-10-16 18:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 18:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 18:32 UTC, Edheltur commented on tasks/18.html
> +                .global-scope > div:hover
➕

2017-10-16 18:35 UTC, Edheltur commented
🍏

2017-10-17 14:19 UTC, Vittly approved these changes

2017-10-17 14:20 UTC, Vittly commented
Молодец

2017-10-17 14:24 UTC, closed without merging