xxx
urfu-2017/markup-task-2 pull request #32
Opened 2017-10-12 19:08 UTC by trszdev

2017-10-12 19:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-12 19:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 10:43 UTC, Mokoshka requested changes

2017-10-19 10:43 UTC, Mokoshka commented on tasks/1.html
> +                    article :nth-child(3)
Давай здесь воспользуемся селектором без nth-child

2017-10-19 10:43 UTC, Mokoshka commented on tasks/11.html
> +                }
Если я введу валидный email инпут должен подсветиться зеленым
![css 2000 2017-10-18 13-01-57](https://user-images.githubusercontent.com/14892550/31707067-92ff8db6-b404-11e7-8323-e808a2fb49da.png)

2017-10-19 10:43 UTC, Mokoshka commented on tasks/12.html
> +                article div:nth-child(2n + 1):not(:nth-child(5))
Сложный селектор, можно проще. Советую почитать про псевдокласс empty

2017-10-19 10:43 UTC, Mokoshka commented on tasks/13.html
> +                article :nth-child(4n + 1) :first-child
Снова сложный селектор, есть псевдокласс, который поможет решить задачку проще

2017-10-19 10:43 UTC, Mokoshka commented on tasks/16.html
> +                }
Зачем столько important? Может можно повысить специфичность другим образом?

2017-10-19 10:43 UTC, Mokoshka commented on tasks/18.html
> +                }
В этой задаче навожу рядом с квадратиком и получаю такой эффект 
![2017-10-18 13 19 05](https://user-images.githubusercontent.com/14892550/31707914-05a6742c-b407-11e7-826a-6ece8da6a3b5.png)
Так быть не должно

2017-10-19 10:43 UTC, Mokoshka commented on tasks/19.html
> +                    background: white;
Давай не будем оставлять браузеру возможности самому решать как отображать цвета. Лучше указывать hex-код

2017-10-19 10:43 UTC, Mokoshka commented on tasks/4.html
> +                }
Эту задачу можно решить, использовав один селектор. Сделаешь?

2017-10-19 10:43 UTC, Mokoshka commented on tasks/5.html
> +                input:checked + br + .tab
Будет неудобно, если между .tab и input будут еще элементы. Есть решение более универсальное

2017-10-19 10:43 UTC, Mokoshka commented on tasks/6.html
> +                }
![css 2000 2017-10-19 15-35-32](https://user-images.githubusercontent.com/14892550/31767054-2c9438e4-b4e3-11e7-8cc0-ac4ca1606ffe.png)

2017-10-19 10:43 UTC, Mokoshka commented on tasks/9.html
> +                    color: black;
Давай добавим hex-код

2017-10-19 10:43 UTC, Mokoshka commented on tasks/9.html
> +                }
В этом задании при наведении на link ссылка становится полупрозрачной, это неправильно.
Так же при наведении на посещенную ссылку, текст остается такого же цвета, а должен стать розовым

2017-10-19 15:26 UTC, trszdev commented on tasks/16.html
> +                }
А чего плохого?

2017-10-19 15:54 UTC, trszdev commented on tasks/18.html
> +                }
Я не знаю как это исправить

2017-10-19 15:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 16:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 16:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 16:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 05:25 UTC, trszdev commented on tasks/9.html
> +                }
https://github.com/urfu-2017/markup-task-2/pull/32/commits/041bfc0e507f8186dedfa9e04bce995fe9e56941

2017-10-22 12:48 UTC, Mokoshka commented on tasks/16.html
> +                }
important можно переопределить лишь инлайновыми стилями, что не есть хорошо.
Поэтому в будущем использование important может выстрелить в ногу и причинить много боли

2017-10-22 13:08 UTC, Mokoshka requested changes

2017-10-22 13:08 UTC, Mokoshka commented on tasks/1.html
> +                    article > .c1 + div
А почему не воспользовался id?

2017-10-22 13:08 UTC, Mokoshka commented on tasks/13.html
> +                article > div > div:only-of-type
Зачем так указывать такую вложенность элементов? Просто div:only-of-type не подойдет?

2017-10-22 13:08 UTC, Mokoshka commented on tasks/4.html
> +                article > h1 ~ article:not(:first-of-type)
А сможешь сделать селектор не используя дополнительные элементы. Если не будет h1, то границы не отобразятся

2017-10-22 13:08 UTC, Mokoshka commented on tasks/9.html
> +                .link:not([href]):hover:not(:active)
active зачем?

2017-10-22 13:09 UTC, Mokoshka commented on tasks/18.html
> +                }
Можно не исправлять, такое поведение допустимо

2017-10-23 06:01 UTC, trszdev commented on tasks/1.html
> +                    article > .c1 + div
линтовщик ругается почемуто(

2017-10-23 06:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-23 06:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 06:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 06:09 UTC, trszdev commented on tasks/16.html
> +                }
079ad33

2017-10-23 06:10 UTC, trszdev commented on tasks/13.html
> +                article > div > div:only-of-type
458fe76

2017-10-23 06:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 06:11 UTC, trszdev commented on tasks/4.html
> +                article > h1 ~ article:not(:first-of-type)
b7a0783

2017-10-23 06:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 06:17 UTC, trszdev commented on tasks/9.html
> +                .link:not([href]):hover:not(:active)
0acdf94

2017-10-23 14:00 UTC, Mokoshka commented on tasks/1.html
> +                    article > .c1 + div
Надо подтянуть изменения для линтера.
Можешь привести свой локальный файл .stylelintrc.json к такому виду https://github.com/urfu-2017/markup-task-2/blob/master/.stylelintrc.json

2017-10-23 14:04 UTC, Mokoshka requested changes
Поправишь линтер и замечания ниже и закрою задачу

2017-10-23 14:04 UTC, Mokoshka commented on tasks/16.html
> +                div.c1 + div.c2.c3.c4.c5.c6
Выглядит страшно. Селектор с id сильно повысит специфичность. Поправь линтер и используй id

2017-10-23 14:04 UTC, Mokoshka commented on tasks/5.html
> +                    color: white;
Лучше использовать hex-коды для цветов, чтобы не давать возможности браузерам самим определять как отобразить цвет

2017-10-23 16:40 UTC, trszdev commented on tasks/5.html
> +                    color: white;
42be77a

2017-10-23 16:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 16:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 16:54 UTC, trszdev commented on tasks/1.html
> +                    article > .c1 + div
b7ceb19

2017-10-23 16:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-24 05:38 UTC, Mokoshka approved these changes

2017-10-24 05:38 UTC, closed without merging