Нестерова Татьяна
urfu-2017/markup-task-2 pull request #33
Opened 2017-10-12 19:36 UTC by tatiannesterova

2017-10-12 19:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 17:01 UTC, mokhov requested changes
Почти всё гут, но в 6-й задаче надо быть повнимательнее.
🍅

2017-10-13 17:01 UTC, mokhov commented on tasks/11.html
> +                input:focus
Из-за фокуса не понятно валидно ли то что введено или нет

2017-10-13 17:01 UTC, mokhov commented on tasks/12.html
> +                div:nth-child(2n-1)
Подумай как можно решить эту задачу без `nth-of-type` (подсказка: div'ы не случайно были написаны так как написаны)

2017-10-13 17:01 UTC, mokhov commented on tasks/13.html
> +                div div:only-of-type
Зачем нужен первый div?

2017-10-13 17:01 UTC, mokhov commented on tasks/16.html
> +                .global-scope div.c2.c3.c4.c5.c6
Нужно ли перечислять все классы?

2017-10-13 17:01 UTC, mokhov commented on tasks/3.html
> +                div > div
Нужен ли здесь `>`?

2017-10-14 09:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-14 10:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-14 17:26 UTC, mokhov commented
👌

2017-10-14 17:26 UTC, closed without merging