First try
urfu-2017/markup-task-2 pull request #34
Opened 2017-10-12 19:56 UTC by nosovandrew

Носов Андрей

2017-10-12 19:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 04:24 UTC, savichev-igor requested changes
В целом 🆗

🍅

2017-10-16 04:24 UTC, savichev-igor commented on tasks/1.html
> +                    aside
А почему не объединишь этот стиль с предыдущим?

2017-10-16 04:24 UTC, savichev-igor commented on tasks/2.html
> +                .c1 + .c2
А почему ты здесь `+` применил?

2017-10-16 04:24 UTC, savichev-igor commented on tasks/3.html
> +                div > div
В принципе ок, но можно было и обычную вложенность использовать)

2017-10-16 04:24 UTC, savichev-igor commented on tasks/4.html
> +                .global-scope > article:not(:first-of-type)
Слишком сложно, попробуй сделать, используя лишь два тэга

2017-10-16 04:24 UTC, savichev-igor commented on tasks/5.html
> +                    <input id="checkbox" type="checkbox" checked><br>
`HTML` править нельзя

2017-10-16 04:24 UTC, savichev-igor commented on tasks/5.html
> +                .global-scope :last-child
Нерабочее решение

2017-10-16 04:24 UTC, savichev-igor commented on tasks/7.html
> +                    opacity: .5;
Я бы на половину урезал прозрачность

2017-10-16 04:24 UTC, savichev-igor commented on tasks/8.html
> +                li > a[target*='_blank']
В задании требуется выделить только ссылки на внешние, относительно my-site.ru, ресурсы

Здесь же этого не выполняется

2017-10-16 04:24 UTC, savichev-igor commented on tasks/9.html
> +                article > a[href]:link
`article >` здесь избыточен, кроме того нужно всегда стараться использовать селектор класса, если это позволяет вёрстка

2017-10-16 04:24 UTC, savichev-igor commented on tasks/10.html
> +                .title:first-letter
Псевдоэлементы принято использовать с `::`

2017-10-16 04:24 UTC, savichev-igor commented on tasks/11.html
> +                input:not(:valid)
Можно использовать `invalid`

2017-10-16 04:24 UTC, savichev-igor commented on tasks/11.html
> +                input:hover
`:focus`

2017-10-16 04:24 UTC, savichev-igor commented on tasks/13.html
> +                div > div:only-of-type
Зачем здесь `div > `?

2017-10-16 04:24 UTC, savichev-igor commented on tasks/15.html
> +                li > a[href$='.zip']:after
`::after`

2017-10-16 04:24 UTC, savichev-igor commented on tasks/14.html
> +                li:before
`::before`

2017-10-16 04:24 UTC, savichev-igor commented on tasks/15.html
> +                li > a[href$='.zip']:after
А если я добавлю ещё одну ссылку, где в названии будет `.zip`?

2017-10-16 04:24 UTC, Savichev-Igor commented on tasks/16.html
> +                    background-color: #6698ff !important;
`!important` желательно не использовать там, где нет необходимости

2017-10-16 04:24 UTC, Savichev-Igor commented on tasks/17.html
> +                input:checked ~ input
`outline` должен уходить, если `input:checked` за чекнутым инпутом

2017-10-16 04:24 UTC, Savichev-Igor commented on tasks/18.html
> +                div
🆗

2017-10-16 04:24 UTC, Savichev-Igor commented on tasks/18.html
> +                .global-scope:hover div:not(:hover)
Попробуй сделать здесь с использованием двух тэгов и одного псевдокласса

2017-10-16 04:24 UTC, Savichev-Igor commented on tasks/18.html
> +                div:hover
А здесь добавить ещё один тэг, чтобы оно работало, учитывая условия ниже

2017-10-16 04:24 UTC, Savichev-Igor commented on tasks/19.html
> +                div > div
Здесь я бы сделал просто `div:empty`

2017-10-16 04:24 UTC, Savichev-Igor commented on tasks/19.html
> +                div:not(:empty)
А здесь обычный `div`

Итого, учитывая решение ниже: у нас используется 2 тэга и 1 псевдоселектор, вместо 2 тэгов и 2 псевдоселекторов, а работает также

2017-10-16 04:24 UTC, Savichev-Igor commented on tasks/19.html
> +                div:nth-child(1) > div:nth-child(4)
Я бы упростил до `:first-child` и :`last-child`

2017-10-16 04:24 UTC, Savichev-Igor commented on tasks/19.html
> +                div:nth-child(4) > div:nth-child(1)
Ну а здесь уж догадайся, как бы упростить)

2017-10-16 04:24 UTC, Savichev-Igor commented on tasks/20.html
> +                div > div:nth-last-child(n+3),
почему не используешь класс вместо `div`, если есть возможность?

2017-10-16 15:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 15:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 15:23 UTC, nosovandrew commented on tasks/15.html
> +                li > a[href$='.zip']:after
Я же использую $, то есть проверяю, чтобы .zip был именно концом.

2017-10-16 17:45 UTC, Savichev-Igor commented
Незначительные замечания остались, но в целом хорошо

2017-10-16 17:46 UTC, savichev-igor approved these changes
Незначительные замечания остались, но в целом ок

2017-10-16 17:46 UTC, Savichev-Igor commented on tasks/1.html
> +
Что это?

2017-10-16 17:46 UTC, Savichev-Igor commented on tasks/1.html
> +
А это?

2017-10-16 17:46 UTC, Savichev-Igor commented on tasks/15.html
> +                a[href$='.zip']::after
Добавь атрибут `download ` в выборку

2017-10-16 17:46 UTC, Savichev-Igor commented on tasks/5.html
> +                input:checked ~ .tab
На дефолтные стили я бы не полагался, их могут переопределить

2017-10-16 17:46 UTC, closed without merging

2017-10-16 17:58 UTC, nosovandrew commented on tasks/1.html
> +
Это случайно

2017-10-16 17:59 UTC, nosovandrew commented on tasks/1.html
> +
Eslint просит так сделать

2017-10-16 18:02 UTC, Savichev-Igor commented on tasks/1.html
> +
Очень странно

2017-10-16 18:06 UTC, nosovandrew commented
А почему вы не зачли мне 20 задачу?

2017-10-16 18:10 UTC, Savichev-Igor commented
Если бы я тебе её не зачёл, то пулл бы не был принят

2017-10-16 18:28 UTC, nosovandrew commented
Просто у меня нет желтой метки "extra", и на hruborg темная звездочка

2017-10-16 18:29 UTC, nosovandrew commented on tasks/15.html
> +                a[href$='.zip']::after
a[href$='.zip'][download]::after должно быть так?

2017-10-16 18:30 UTC, Savichev-Igor commented
За 20-ю задачу нигде не гарантировалась звёздочка

2017-10-16 18:32 UTC, Savichev-Igor commented
Звёздочка в этом задании ставится на усмотрение ментора в зависимости от изящности и лаконичности решения, а ещё на какой итерации оно было достигнуто

2017-10-16 18:41 UTC, Savichev-Igor commented on tasks/15.html
> +                a[href$='.zip']::after
Да, потому что в адресе ссылки может просто случайно оказаться `.zip`, хотя она не должна ничего скачивать, поэтому мы перестраховываемся атрибутом `download`