first version
urfu-2017/markup-task-2 pull request #35
Opened 2017-10-12 21:37 UTC by ArtyMgn

2017-10-12 21:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-13 10:06 UTC, f0rmat1k requested changes
Из критичных замечаний ток про ссылки.

2017-10-13 10:06 UTC, f0rmat1k commented on tasks/1.html
> +                    div.c1
А для чего ты добавил `div` к `.c1` в селекторе?

2017-10-13 10:06 UTC, f0rmat1k commented on tasks/9.html
> +                a[href='https://ya.ru']:hover
Если ссылка стала посещенная, то перестает работать hover, а должен.

2017-10-13 10:06 UTC, f0rmat1k commented on tasks/16.html
> +                article div:first-child
А для чего здесь каскад?

2017-10-13 10:06 UTC, f0rmat1k commented on tasks/16.html
> +                div.c7
Глобальный вопрос. Это не критично, но ты зачастую используешь сильно бОльшие по весу селекторы, чем достаточно для решения.

2017-10-13 13:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-14 06:42 UTC, closed without merging