Тощев Иван
urfu-2017/markup-task-2 pull request #38
Opened 2017-10-13 09:55 UTC by ToshchevIvan

2017-10-13 09:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-13 09:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-13 10:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 06:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 15:42 UTC, bazhenova requested changes
Привет) Есть несколько замечаний, их нужно поправить. А в остальном все хорошо 🍅

2017-10-15 15:42 UTC, bazhenova commented on tasks/1.html
> +                    :empty
Давай не будем использовать псевдокласс без указания тега или класса

2017-10-15 15:42 UTC, bazhenova commented on tasks/1.html
> +                    div.c1
Здесь можно не указывать `div`

2017-10-15 15:42 UTC, bazhenova commented on tasks/1.html
> +                    div.c1 + div
Тут тоже можно просто написать .c1 + div

2017-10-15 15:42 UTC, bazhenova commented on tasks/1.html
> +                    div.c1 + div
Если бы ты поправил правила для линтера как советовали, то в этом месте можно было бы написать намного проще))

2017-10-15 15:42 UTC, bazhenova commented on tasks/2.html
> +                div.c1
В этом файле можно везде не указывать `div`

2017-10-15 15:42 UTC, bazhenova commented on tasks/3.html
> +                article > div
Так как в одном файле может быть много `article`, давай лучше будем указывать класс

2017-10-15 15:42 UTC, bazhenova commented on tasks/5.html
> +                input[type='checkbox']:checked ~ div.tab
В конце можно не указывать `div`

2017-10-15 15:42 UTC, bazhenova commented on tasks/5.html
> +                    color: white;
Цвета лучше указывать в hex

2017-10-15 15:42 UTC, bazhenova commented on tasks/7.html
> +                div:not(:first-child):not(:last-child) img
Давай попробуем написать тут намного проще. Подумай, что объединяет полупрозрачные картинки

2017-10-15 15:42 UTC, bazhenova commented on tasks/9.html
> +                a:not([href]):not(:active):hover
Слишком много `not`. Давай перепишем по-другому

2017-10-15 15:42 UTC, bazhenova commented on tasks/16.html
> +                .global-scope div.c2.c3.c4.c5.c6
А нужно ли столько много классов указывать?

2017-10-15 15:42 UTC, bazhenova commented on tasks/16.html
> +                div.c7
Здесь можно не писать `div`

2017-10-15 15:42 UTC, bazhenova commented on tasks/19.html
> +                    background: white;
Цвет в hex

2017-10-15 15:42 UTC, bazhenova commented on tasks/20.html
> +                div > div:first-child:nth-last-child(n+3) ~ div,
А нужен ли тут `:first-child`? И во втором правиле

2017-10-19 09:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 09:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 09:37 UTC, ToshchevIvan commented on tasks/1.html
> +                    div.c1 + div
Добрый день) Дело не только в линтере, но и в том, что на лекции нам достаточно однозначно сказали не использовать id для оформления. Поэтому старался избегать, в том числе, и в 16 задании.

2017-10-19 09:37 UTC, ToshchevIvan commented on tasks/16.html
> +                .global-scope div.c2.c3.c4.c5.c6
Просто подумал, что это - задание на повышение специфичности селектора)

2017-10-19 09:37 UTC, ToshchevIvan commented on tasks/7.html
> +                div:not(:first-child):not(:last-child) img
Я не против, но мне показалось, что на внешний вид элементов влияет скорее расположение, чем наличие аттрибута alt, и при добалении/удалении alt было бы странно увидеть, что прозрачность поменялась.

2017-10-19 10:21 UTC, bazhenova reviewed
Осталось одно замечание. Поправь, пожалуйста) 🍅

2017-10-19 10:21 UTC, bazhenova commented on tasks/9.html
> +                    opacity: .5;
Если навожу на первую ссылку, то цвет становится бледным. Такая логика подходит для второй ссылки, но не для первой

2017-10-19 10:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 10:39 UTC, bazhenova approved these changes

2017-10-19 10:40 UTC, bazhenova commented
Молодец! Хорошо поработал)

2017-10-19 10:40 UTC, closed without merging