Решетников Артем
urfu-2017/markup-task-2 pull request #39
Opened 2017-10-13 11:56 UTC by Xrias

2017-10-13 11:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-13 12:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-13 12:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-13 12:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-13 12:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 19:55 UTC, Grimfrid commented on tasks/1.html
> +                        background: #6698ff;
На изображении 2 квадрата имеют одинаковый фон, надо подобрать такой селектор, который установит сразу обоим. Что-то вроде:
```
селектор1, селектор2 {
    background: #6698ff;
}
```

2017-10-15 19:56 UTC, Grimfrid commented on tasks/1.html
> +                    div
тут нужен селектор по `id`

2017-10-15 19:57 UTC, Grimfrid commented on tasks/2.html
> +                div.c1.c2
Во всех этих селекторах достаточно указать только класс, `div` лишний

2017-10-15 20:00 UTC, Grimfrid commented on tasks/5.html
> +                input:checked ~ div
тут вместо `div` нужен селектор класса, иначе стили применятся ко всем `div` которые могут случайно оказаться рядом

2017-10-15 20:02 UTC, Grimfrid commented on tasks/6.html
> +                a
Неплохо придумал, но тут суть задания в том, что ссылка на vk должна быть синего цвета, а на яндекс красного. В твоем случае если поменять теги местами, то уже так не будет. Тут нужно написать селектор использующий атрибут ссылки

2017-10-15 20:06 UTC, Grimfrid commented on tasks/7.html
> +               div:not(:nth-last-of-type(3n+1))
Неплохо, но смысл немного в другом, ты привязываешься к порядку, но обрати внимание на разметку полупрозрачных картинок - она отличается от других, по-этому они и полупрозрачные. Используй это в селекторе

2017-10-15 20:08 UTC, Grimfrid commented on tasks/8.html
> +                [target='_blank']
`target='_blank'` может использоваться и для открытия ссылок на тот же ресурс, по-этому тут надо использовать `href`

2017-10-15 20:11 UTC, Grimfrid commented on tasks/9.html
> +                [href='https://ya.ru']:hover
Попробуй это задание сделать лучше:
1) Использовать `.link`
2) Не использовать `url` в стилях, тут достаточно наличия `href`
3) Написать стили не используя `!important`
4) Не используя соседние селекторы

Если будут вопросы почему и как, пиши в слак или задавай тут

2017-10-15 20:12 UTC, Grimfrid commented on tasks/11.html
> +                [type='email']:focus
в этом задании надо использвать тег `input` и псевдоклассы, которые выставляются после валидации адреса

2017-10-15 20:14 UTC, Grimfrid commented on tasks/12.html
> +                div:nth-last-of-type(6n+1)
В этом задании, если обратить внимание на разметку, то какие-то теги "пустые" а какие-то нет, попробуй это использовать

2017-10-15 20:16 UTC, Grimfrid commented on tasks/13.html
> +                div:nth-child(4n+1) > div:nth-child(1)
Снова привязываешься к порядку, а тут есть особенность, нужно выделить `div`, которые внутри `div`. Подсказка `:only-of-type`

2017-10-15 20:17 UTC, Grimfrid commented on tasks/16.html
> +                div
Тут можно подобрать селекторы так, чтобы `!important` был только в одному случае, попробуй

2017-10-15 20:19 UTC, Grimfrid commented on tasks/19.html
> -                /* your styles here */
Тут все круто! Молодец!

2017-10-15 20:21 UTC, Grimfrid reviewed
🍅

2017-10-16 08:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 08:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 08:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 09:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 19:50 UTC, Grimfrid commented on tasks/11.html
> +                [type='email']:focus
вместо `[type='email']` тоже input, чтобы было единообразно

2017-10-16 19:55 UTC, Grimfrid requested changes
Молодец! Еще хорошая практика при использовании селектора атрибутов указывать тег. А при использовании селектора класса или id тег не указывают. Давай поправим это!

🍅

2017-10-16 20:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 20:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 20:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 20:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 20:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 20:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 20:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 20:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 17:14 UTC, Grimfrid commented
🍏

2017-10-17 17:14 UTC, closed without merging