Медведев Денис
urfu-2017/markup-task-2 pull request #4
Opened 2017-10-10 19:08 UTC by DenyDeny

[Посмотреть решение](https://rawgit.com/DenyDeny/markup-task-2/master/index.html)

2017-10-10 19:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 09:58 UTC, v3new requested changes
🍅

2017-10-15 09:58 UTC, v3new commented on tasks/1.html
> +                    .global-scope div
повышение специфичности при помощи `.global-scope` лишнее, это общее замечание ко всем задачам

2017-10-15 09:58 UTC, v3new commented on tasks/4.html
> +                .global-scope article:not(:nth-of-type(1))
слишком сложно, попробуй решить через смежные селекторы

2017-10-15 09:58 UTC, v3new commented on tasks/5.html
> +                input[type='checkbox']:checked ~ .tab
для чего тут повышение специфичности `[type='checkbox']` ?

2017-10-15 09:58 UTC, v3new commented on tasks/7.html
> +                .global-scope img[alt]
при помощи `:not` можно решить одним правилом

2017-10-15 09:58 UTC, v3new commented on tasks/8.html
> +                a[href^='https'],
что произойдет, если ссылка будет вести на http://my-super-site.ru ?

2017-10-15 09:58 UTC, v3new commented on tasks/9.html
> +                .link[href]:hover + .link
можно легко сделать более универсально, при помощи конструкции `:not([href])`

2017-10-15 09:58 UTC, v3new commented on tasks/11.html
> +                input[type='email']:valid
зачем повышение?

2017-10-15 09:58 UTC, v3new commented on tasks/12.html
> +                    background-color: #ff6;
обрати внимание, что content оранжевых фигур отличается

2017-10-15 09:58 UTC, v3new commented on tasks/13.html
> +                .global-scope > div div:only-of-type
излишне специфичный селектор

2017-10-15 09:58 UTC, v3new commented on tasks/14.html
> +                .global-scope ul li::before
ещё раз напомню, что `.global-scope ul` тут ни к чему

2017-10-15 09:58 UTC, v3new commented on tasks/16.html
> +                    background-color: #ffb366;
можно взять этот цвет за базу, а первый элемент выделить через `:first-child`

2017-10-15 09:58 UTC, v3new commented on tasks/17.html
> +                input[type='checkbox']
`outline` должен быть только на чекбоксах правее выделенного

2017-10-15 09:58 UTC, v3new commented on tasks/18.html
> +                .global-scope div:hover
на эталоне есть три состояния прозрачности

2017-10-15 09:58 UTC, v3new commented on tasks/20.html
> +                .red-gt2 div:nth-last-child(n + 3):first-child ~ div,
зачем `:first-child` ?

2017-10-15 12:39 UTC, DenyDeny commented on tasks/11.html
> +                input[type='email']:valid
На случай, что если были бы инпуты другого типа. Но теперь я понял, что нужно простыми путями решать задачи )

2017-10-15 12:45 UTC, DenyDeny commented on tasks/12.html
> +                    background-color: #ff6;
Спасибо. Впервые применил селектор :empty.

2017-10-15 12:46 UTC, DenyDeny commented on tasks/14.html
> +                .global-scope ul li::before
+

2017-10-15 13:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 08:56 UTC, v3new commented
Мой косяк, что надолго задержал ревью, сорри. Всё хорошо, только ну будущее - делай `rebase` коммитов, чтобы правки вносить одним, а не по три!

2017-10-23 08:59 UTC, v3new commented
Молодец 👍

2017-10-23 08:59 UTC, v3new approved these changes

2017-10-23 08:59 UTC, closed without merging