Акулин Максим
urfu-2017/markup-task-2 pull request #40
Opened 2017-10-13 15:23 UTC by Aristarch12

2017-10-13 15:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 07:42 UTC, evilj0e requested changes
В целом, молодец. Внимательнее читай задания и не пиши лишнего.

2017-10-15 07:42 UTC, evilj0e commented on tasks/10.html
> +                    color: red;
Список цветов определён заранее. Этот цвет в него не входит.

2017-10-15 07:42 UTC, evilj0e commented on tasks/11.html
> +                input + input
А что если у тебя поля ввода не стоят рядом?
Поищи, есть мета-аттрибуты, которые отвечают за то, валидно поле или нет.

2017-10-15 07:42 UTC, evilj0e commented on tasks/12.html
> +                    background: #ffb366;
В задании указано, что нужно решить с помощью `background-color`

2017-10-15 07:42 UTC, evilj0e commented on tasks/12.html
> +                div:empty
Можешь написать свои стили так, чтобы порядок элементов со своими стилями не играл роли?

2017-10-15 07:42 UTC, evilj0e commented on tasks/12.html
> +                    background: #ff6;
Цвет некорректный

2017-10-15 07:42 UTC, evilj0e commented on tasks/13.html
> +                    background: #ff6698;
Прочитай внимательно задание

2017-10-15 07:42 UTC, evilj0e commented on tasks/15.html
> +                a[href$='.zip']::after
А что если у тебя будет просто ссылка на zip-архив без скачивания?
Исправь правило, чтобы оно добавляло стрелку только к "скачиваемым" ссылкам.

2017-10-15 07:42 UTC, evilj0e commented on tasks/17.html
> +                :checked ~ input
Стоит сделать более строгое правило.

2017-10-15 07:42 UTC, evilj0e commented on tasks/18.html
> +                article.global-scope div
Классы лишние

2017-10-15 07:42 UTC, evilj0e commented on tasks/18.html
> +                    opacity: .5    ;
Странный отступ после .5

2017-10-15 07:42 UTC, evilj0e commented on tasks/19.html
> +                    background: orange;
Цвета неверные

2017-10-15 07:42 UTC, evilj0e commented on tasks/19.html
> +                div div
Пустые дивы имеют белый фон. Это правило не покроет все случаи.

2017-10-15 07:42 UTC, evilj0e commented on tasks/19.html
> +                    background: orange;
Прочитай внимательно задание

2017-10-15 07:42 UTC, evilj0e commented on tasks/19.html
> +                div:first-child div:nth-of-type(4)
А что, если элементов больше? Нам нужно раскрасить последний

2017-10-15 07:42 UTC, evilj0e commented on tasks/2.html
> +                    background: #6698ff;
Прочитай внимательно задание.

2017-10-15 07:42 UTC, evilj0e commented on tasks/3.html
> +                    background: #6698ff;
Прочитай внимательно задание

2017-10-15 07:42 UTC, evilj0e commented on tasks/5.html
> +                :checked ~ div
Привяжись к классу, а не тегу.
А что будет, если инпут не отмечен?
Прочитай задание, там нужно использовать другое правило.

2017-10-15 07:42 UTC, evilj0e commented on tasks/6.html
> +                [href*='yandex']
Стоит дополнительно указать тег
Где правило для ссылок на vk?

2017-10-15 07:42 UTC, evilj0e commented on tasks/7.html
> +                div > img:not([alt])
Не думаешь, что `div >` – лишнее?

2017-10-15 07:42 UTC, evilj0e commented on tasks/8.html
> +                [target='_blank']
В задании указано, что нужно выделить ссылки на внешние сайты.
Аттрибут `target` тебе с этим не поможет.

2017-10-15 07:42 UTC, evilj0e commented on tasks/9.html
> +                a:not([href]):active
Лишнее

2017-10-15 08:34 UTC, evilj0e commented
🍅

2017-10-19 09:42 UTC, Aristarch12 commented on tasks/12.html
> +                    background: #ffb366;
_"Решите задачу, используя background: <color>"_
По-моему, всё-таки, нет.

2017-10-19 09:49 UTC, Aristarch12 commented on tasks/12.html
> +                    background: #ff6;
Почему некорректный? Если ты утверждаешь, что нужно писать ffff66, то это не проходит проверку линтера
_21:17  ×  Expected "#ffff66" to be "#ff6"   color-hex-length_

2017-10-19 09:51 UTC, Aristarch12 commented on tasks/12.html
> +                div:empty
Не понял, что означает _"порядок элементов со своими стилями не играл роли"_. Если поменять два правила местами, то визуально ничего не изменится (из-за специфичности)

2017-10-19 09:53 UTC, Aristarch12 commented on tasks/13.html
> +                    background: #ff6698;
Не понимаю, что я прочитал невнимательно

2017-10-19 10:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 10:13 UTC, Aristarch12 commented on tasks/2.html
> +                    background: #6698ff;
Не понимаю, что не так

2017-10-19 10:13 UTC, Aristarch12 commented on tasks/3.html
> +                    background: #6698ff;
Не понимаю, что не так

2017-10-19 10:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 10:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 10:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-24 08:31 UTC, evilj0e commented on tasks/12.html
> +                    background: #ffb366;
Да, я оказался не прав. Моя ошибка

2017-10-24 08:38 UTC, evilj0e approved these changes

2017-10-24 08:38 UTC, evilj0e commented on tasks/12.html
> +                div:empty
Согласен с тобой. Мой комментарий в этом случае лишний

2017-10-24 08:38 UTC, evilj0e commented on tasks/12.html
> +                    background: #ff6;
Нет, я не про формат. Я про значение цвета. Они не совпадают.

2017-10-24 08:38 UTC, evilj0e commented on tasks/12.html
> +                    background: #ff6;
В ридми задания указаны все цвета

2017-10-24 08:38 UTC, evilj0e commented on tasks/2.html
> +                    background: #6698ff;
В заданиях про фон я прочитал неверно и ожидал, что должно быть решение с `background-color`

2017-10-24 08:39 UTC, evilj0e commented
:star:

2017-10-24 08:39 UTC, closed without merging

2017-10-24 09:28 UTC, evilj0e commented
Исправил теги. Из-за того, что не увидел ПР на дашборде время вышло.