What about this?
urfu-2017/markup-task-2 pull request #45
Opened 2017-10-13 19:57 UTC by King-Of-Plague1

2017-10-13 19:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 16:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 16:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 18:23 UTC, mokhov requested changes
В 11 я не узнаю что введённый email правильный:
<img width="653" alt="css 2000 2017-10-16 01-21-09" src="https://user-images.githubusercontent.com/357689/31587696-5909a826-b210-11e7-8d25-9bab4bba9930.png">

В 17-м задании нужно чтобы красной обводкой выделялись все чекбоксы, после выбранного.
🍅

2017-10-15 18:23 UTC, mokhov commented on tasks/7.html
> +                div img[]
Зачем нужны `[]`?

2017-10-15 18:23 UTC, mokhov commented on tasks/16.html
> +                div[class]
Почему выбрал селектор атрибута?

2017-10-16 18:36 UTC, King-Of-Plague1 commented on tasks/7.html
> +                div img[]
скобочки означают, что в img не переданы какие-то дополнительные атрибуты(если я правильно понял) и без них не работает

2017-10-16 18:50 UTC, King-Of-Plague1 commented on tasks/16.html
> +                div[class]
Первое что пришло в голову, а чем он плох в данной ситуации?

2017-10-16 19:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-18 07:49 UTC, mokhov commented on tasks/16.html
> +                div[class]
Тем что можно короче

2017-10-18 07:49 UTC, mokhov commented on tasks/7.html
> +                div img[]
Точно так же можно их вообще опустить

2017-10-18 07:49 UTC, mokhov commented
🅾️

2017-10-18 07:50 UTC, closed without merging