Стихин Семен
urfu-2017/markup-task-2 pull request #49
Opened 2017-10-14 07:30 UTC by samstikhin

Done all

2017-10-14 07:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 07:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 08:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 08:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 08:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 12:02 UTC, dotokoto requested changes
Привет! Я проверила, некоторые примеры работают не так, как надо. Поправь замечания, пожалуйста. И когда поправишь, лучше напиши мне в Слак, чтобы я быстрее второй раз посмотрела.

2017-10-16 12:02 UTC, dotokoto commented on tasks/1.html
> +                        background-color: #6697ff;
Можно объединить с первым правилом:
```
div,
aside 
{
background-color: #6697ff;
}
```

2017-10-16 12:02 UTC, dotokoto commented on tasks/3.html
> +                    border: 0;
Лучше пытаться переопределять как можно меньше правил. Попробуй переписать первый селектор, используя `>`, чтобы не пришлось переписывать border у внутренних дивов

2017-10-16 12:02 UTC, dotokoto commented on tasks/4.html
> +                hr + article
Здесь можно обойтись одним правилом, использовав `+`, чтобы выбрать все article кроме первого

2017-10-16 12:02 UTC, dotokoto commented on tasks/7.html
> +                img[alt='css 3 logo']
Тут тоже можно обойтись только одним селектором, изменив условие для атрибута `alt`

2017-10-16 12:02 UTC, dotokoto commented on tasks/8.html
> +                a[target='_blank']
Работает, но не подходит под условие задачи. По условию нужно выделить внешние относительно `my-site.ru` ссылки

2017-10-16 12:02 UTC, dotokoto commented on tasks/9.html
> +                a[href='https://ya.ru']:active
У псевдоссылок нет href, ориентируйся на его наличие/отсутствие.
И еще, верхняя ссылка черная, а должна быть синяя, и не меняет цвет на зеленый при нажатии.

2017-10-16 12:02 UTC, dotokoto commented on tasks/11.html
> +                input:nth-child(2)
В задании нужно, чтобы инпут менял цвет в зависимости от валидности контента внутри, а не просто имел определенный цвет рамок

2017-10-16 12:02 UTC, Dotokoto commented on tasks/12.html
> +                div:nth-child(5)
Так, конечно, все задания можно с `nth-child` решить. Но все-таки хочется разнообразия, а не один и тот же селектор везде использовать :) Здесь предполагалось использование `empty`

2017-10-16 12:02 UTC, Dotokoto commented on tasks/13.html
> +                div:nth-child(9) > div
Здесь можно посмотреть в сторону селектора `:only-of-type`

2017-10-16 12:02 UTC, Dotokoto commented on tasks/16.html
> +                    background-color: #ffff65 !important;
important лучше использовать только в крайних случаях. Здесь 3 цвета из 4 можно задать и без него, попробуй переписать селекторы

2017-10-16 12:02 UTC, Dotokoto commented on tasks/17.html
> +                input[type='checkbox']:checked ~ input[type='checkbox']
Работает неправильно
![css 2000 2017-10-16 16-55-31](https://user-images.githubusercontent.com/8973726/31610797-e28b4adc-b292-11e7-8466-96eaacd70743.png)

2017-10-16 12:02 UTC, Dotokoto commented on tasks/18.html
> +                div:hover
Тоже работает неправильно, при наведении на один все остальные должны становиться более прозрачными

2017-10-16 12:02 UTC, Dotokoto commented on tasks/19.html
> +                }
В этой задаче можно тоже поиграться с разными селекторами, типа `:first-child`, `:last-child`, `:empty`

2017-10-16 12:02 UTC, Dotokoto commented on tasks/20.html
> +                div:nth-child(4) > div
Не соответствует логике задания. Хочется, чтобы красилось именно в зависимости от количества элементов внутри, а не просто внутри двух последних дивов закрасить.
![css 2000 2017-10-16 16-59-39](https://user-images.githubusercontent.com/8973726/31610972-9a058600-b293-11e7-9602-871218429673.png)

2017-10-16 19:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 19:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 19:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 08:25 UTC, dotokoto approved these changes
Посмотрела, основное задание принимаю. Дополнительное пока нет, сейчас все еще красит элементы в двух последних `div`, а не там, где больше трех элементов ( Попробуй посмотреть в сторону селектора `nth-last-child`

2017-10-17 08:25 UTC, dotokoto commented on tasks/11.html
> +                input
Красная рамка должна быть только у invalid инпута

2017-10-18 07:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-18 18:28 UTC, Dotokoto commented on tasks/20.html
> +                div > div:first-child:not(:last-child):not(:nth-last-child(2)) ~ div
На самом деле, то же самое можно было записать проще:
```
div > div:nth-last-child(n+3),
div > div:nth-last-child(n+3) ~ div
```
Но работает так как надо, так что принимаю. Молодец, что доделал доп задание!

2017-10-18 18:28 UTC, closed without merging