Тощилин Сергей
urfu-2017/markup-task-2 pull request #5
Opened 2017-10-10 21:38 UTC by spt30

2017-10-10 21:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-14 22:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-14 22:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-14 23:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 23:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 08:34 UTC, evilj0e requested changes
Старайся писать, как можно короче, меньше используй перегрузки.

2017-10-15 08:34 UTC, evilj0e commented on tasks/1.html
> +                    aside
Правила про div и aside разные?

2017-10-15 08:34 UTC, evilj0e commented on tasks/1.html
> +                    article > div[id='id']
Сложно. Напиши в 3 символа

2017-10-15 08:34 UTC, evilj0e commented on tasks/10.html
> +                article > .title::first-letter
Зачем тебе `article > `?

2017-10-15 08:34 UTC, evilj0e commented on tasks/11.html
> +                article > input:valid
Зачем тебе везде `article >`?

2017-10-15 08:34 UTC, evilj0e commented on tasks/12.html
> +                article > div:empty
В твоём решении важен порядок правил. Можно переписать так, чтобы порядок был не важен. Сможешь?

2017-10-15 08:34 UTC, evilj0e commented on tasks/12.html
> +                article > div:empty
Ну и удали `article >`

2017-10-15 08:34 UTC, evilj0e commented on tasks/13.html
> +                div:nth-child(4n+1) > div
Ты привязался к порядку узла, это плохо. Можно без этого. Посмотри псевдоклассы.

2017-10-15 08:34 UTC, evilj0e commented on tasks/15.html
> +                ul > li > a[href$='.zip']:after
Что в этом правиле лишнее?
В вёрстке есть дополнительный атрибут. Перепиши правило с использованием его.

2017-10-15 08:34 UTC, evilj0e commented on tasks/16.html
> +                article > div
Перепиши максимально без импортантов, используй нормальный id, а не настолько сложную конструкцию, ну и откажись от article >.

2017-10-15 08:34 UTC, evilj0e commented on tasks/17.html
> +                input[type='checkbox']:checked ~ input[type='checkbox']
Совмести два правила в одно.

2017-10-15 08:34 UTC, evilj0e commented on tasks/19.html
> +                article > div:nth-child(4) > div:nth-child(1)
Не завязывайся на номер

2017-10-15 08:34 UTC, evilj0e commented on tasks/19.html
> +                article > div > div
Обрати внимание на содержимое узла и перепиши этот селектор.

2017-10-15 08:34 UTC, evilj0e commented on tasks/2.html
> +                .c1 + .c2
Сложное переопределение. Напиши более явно.

2017-10-15 08:34 UTC, evilj0e commented on tasks/3.html
> +                div > div
Зачем тебе `>`?

2017-10-15 08:34 UTC, evilj0e commented on tasks/5.html
> +                    background: #000;
Читай внимательно задание

2017-10-15 08:34 UTC, evilj0e commented on tasks/6.html
> +                article > a
Завяжись на vk, а не просто на то, что это ссылка

2017-10-15 08:34 UTC, evilj0e commented on tasks/7.html
> +                div > img[alt*='css']
а что если будет другое содержимое у alt?
перепиши всё в один селектор

2017-10-15 08:34 UTC, evilj0e commented on tasks/8.html
> +                a[target='_blank']
таргет небе никак не показывает ведёт ли ссылка на внешний ресурс или нет

2017-10-15 08:34 UTC, evilj0e commented on tasks/9.html
> +                article > a:link
a – это не link?

2017-10-15 08:34 UTC, evilj0e commented on tasks/9.html
> +                article > a[href*='ru']:hover
а что если не ru?

2017-10-15 08:34 UTC, evilj0e commented
🍅

2017-10-15 09:53 UTC, spt30 commented on tasks/1.html
> +                    article > div[id='id']
там это, он при проверке на #id ругался, сказал идентификаторы не юзать. А потом в слаке написали, как это фиксить, но я забыл, поэтому оставил как было. Поправлю)

2017-10-15 10:19 UTC, spt30 commented on tasks/10.html
> +                article > .title::first-letter
так делать не надо? Просто я заметил, что в паре заданий у меня еще нижние ссылки ("Предыдущее" и "Следующее") покрасились. Поэтому обезопасился и перестраховался: понатыкал везде селекторов детей

2017-10-15 10:41 UTC, spt30 commented on tasks/15.html
> +                ul > li > a[href$='.zip']:after
![image](https://user-images.githubusercontent.com/31798669/31584014-306792f8-b1bf-11e7-927e-97a8d0d889ff.png)
там вот такая штука в 0 ссылке тоже есть, так что вроде бы только href$='.zip' подходит

2017-10-15 10:44 UTC, spt30 commented on tasks/15.html
> +                ul > li > a[href$='.zip']:after
или речь про <br>?

2017-10-15 11:34 UTC, spt30 commented on tasks/3.html
> +                div > div
в смысле можно просто с пробелом? ну я подумал, если вдруг мне захочется вписать в div еще один div, он же не должен краситься, поэтому указал ребенка. Исправлю на пробел

2017-10-15 11:38 UTC, spt30 commented on tasks/5.html
> +                    background: #000;
что именно не так? не могу понять
"если стоит галочка, покрасить цвет в белый, фон в черный"
backgroung использовал, color тоже

2017-10-15 12:13 UTC, spt30 commented on tasks/9.html
> +                article > a:link
для непосещенной ссылки же написанно голубой цвет применить
>Псевдокласс :link применяется к ссылкам, которые ещё не посещались пользователем, и задаёт для них стилевое оформление.
не понимаю, что не так

2017-10-15 12:19 UTC, evilj0e commented on tasks/10.html
> +                article > .title::first-letter
Можешь оставить как есть

2017-10-15 12:21 UTC, evilj0e commented on tasks/15.html
> +                ul > li > a[href$='.zip']:after
Сейчас ты добавишь стрелку ко всем-всем ссылкам, которые оканчиваются на .zip, а нужно добавить только к тем, которые скачивают. Посмотри, что за атрибут download у ссылок

2017-10-15 12:25 UTC, evilj0e commented on tasks/5.html
> +                    background: #000;
Можно написать более явно: `background-color: #000`

2017-10-15 12:26 UTC, evilj0e commented on tasks/9.html
> +                article > a:link
Да, согласен.
Я имел ввиду, что тут можно без него обойтись, так как у тебя уже есть правило для `a:visited`

2017-10-15 12:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-15 12:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-15 13:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-15 13:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-15 13:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-15 15:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 15:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 05:48 UTC, evilj0e commented on tasks/8.html
> +				{
Поправь отступы везде

2017-10-16 05:49 UTC, evilj0e commented
Поправь отступы. 
В остальном молодец, селекторы написал лаконично и круто.

2017-10-16 07:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 07:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 07:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 07:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 07:57 UTC, spt30 commented
вроде бы все ровно теперь

2017-10-16 08:43 UTC, evilj0e approved these changes

2017-10-16 08:43 UTC, closed without merging

2017-10-16 09:04 UTC, spt30 commented
а экстры не будет?