Yup.
urfu-2017/markup-task-2 pull request #50
Opened 2017-10-14 09:23 UTC by Damirikys

I'm ready.

2017-10-14 09:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 07:12 UTC, vaseker requested changes
В целом, нормально все. Требуется только упрощение селекторов по всем задачам. Отсутствие комментария к задаче не значит, что на нее не нужно повторно посмотреть и упростить решение.

2017-10-15 07:12 UTC, vaseker commented on tasks/1.html
> +                    div.c1
В учебных задачках нужно компактное и эффективное решение. Не нужно повышать специфичность там, где это не требуется. Тут достаточно обращения к .c1 и #id. По всем задачам нужно упростить селекторы.

2017-10-15 07:12 UTC, vaseker commented on tasks/10.html
> +                p.title::first-letter
лишний p

2017-10-15 07:12 UTC, vaseker commented on tasks/13.html
> +                div > div:only-of-type
👍

2017-10-15 07:12 UTC, vaseker commented on tasks/14.html
> +                ul li::before
~~ul~~

2017-10-15 07:12 UTC, vaseker commented on tasks/16.html
> +                .global-scope div#id1
~~.global-scope div~~

2017-10-15 07:12 UTC, vaseker commented on tasks/19.html
> +                div:nth-child(2) > div:nth-child(2n)
(2n) и (2n+1) можно заменить на even и odd. просто к сведению

2017-10-15 07:12 UTC, vaseker commented on tasks/19.html
> +                div:nth-child(4) > div:first-child
эти кучи дивов и `>` необязательны. можно чуть проще `div:last-child :first-child`

2017-10-15 07:13 UTC, vaseker commented
🍅

2017-10-15 07:17 UTC, vaseker commented on tasks/20.html
> +                .red-gt2:nth-child(n+3) > div
Читерство. Задача не будет выполнена, если в первых .red-gt2 будет более 3х детей
> Выделите все внутренние элементы там, где их больше 2

2017-10-15 07:58 UTC, vaseker commented on tasks/20.html
> +                .red-gt2:nth-child(n+3) > div
Так неверно
<img width="232" alt="2017-10-15 12 57 41" src="https://user-images.githubusercontent.com/1942271/31582876-892d6f1e-b1a8-11e7-8f3c-821d70644b21.png">

Так норм
![20](https://user-images.githubusercontent.com/1942271/31582877-943ed276-b1a8-11e7-8312-127cc7245980.png)

2017-10-15 10:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 11:27 UTC, vaseker commented
🍏

2017-10-15 11:27 UTC, closed without merging