Бородин Георгий
urfu-2017/markup-task-2 pull request #52
Opened 2017-10-14 13:23 UTC by BorodinGeorgy

2017-10-14 13:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 13:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 14:33 UTC, Vittly commented on tasks/18.html
> +                article:hover div:not(:hover)
если поменять порядок с предыдущим правилом - можно сделать короче

2017-10-16 14:35 UTC, Vittly requested changes
🍅 
небольшие замечания

2017-10-16 14:35 UTC, Vittly commented on tasks/4.html
> +                article > article:not(:first-of-type)
а можно короче?

2017-10-16 14:35 UTC, Vittly commented on tasks/8.html
> +                a[href*='//']:not([href*='my-site'])
давай другой признак - покороче

2017-10-16 14:35 UTC, Vittly commented on tasks/9.html
> +                }
давай сгруппируем - те который с href и которые без него

2017-10-16 15:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 14:27 UTC, Vittly approved these changes

2017-10-17 14:27 UTC, Vittly commented
Хорошо, молодец

2017-10-17 14:27 UTC, closed without merging