done
urfu-2017/markup-task-2 pull request #53
Opened 2017-10-14 14:06 UTC by HazipovVF

2017-10-14 14:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 18:02 UTC, msmirnov requested changes
🍅

2017-10-15 18:02 UTC, msmirnov commented on tasks/1.html
> +                    {
Что-то не то с отступами

2017-10-15 18:02 UTC, msmirnov commented on tasks/10.html
> +                .global-scope .title::first-letter
Глобальное замечание: не нужно использовать `.global-scope` в селекторах. Предполагается, что элементы с указанными классами не используются в других частях страницы.

2017-10-15 18:02 UTC, msmirnov commented on tasks/11.html
> +
Здесь нужно использовать только псевдоклассы, указывающие на валидность данных

2017-10-15 18:02 UTC, msmirnov commented on tasks/12.html
> +                .global-scope div
Получается, что для пустого элемента сначала применится этот селектор, а затем следующий. То есть цвет переопределится, что для производительности не хорошо.

2017-10-15 18:02 UTC, msmirnov commented on tasks/13.html
> +                div div:only-of-type
Зачем здесь составной селектор? Первый `div` можно убрать.

2017-10-15 18:02 UTC, msmirnov commented on tasks/16.html
> +                .global-results div.c2.c3.c4.c5.c6
Лучше использовать селектор по id

2017-10-15 18:02 UTC, msmirnov commented on tasks/17.html
> +                }
Слишком сложно, это можно сделать в 1 селектор и не использовать классы `.global-*`

2017-10-15 18:02 UTC, msmirnov commented on tasks/18.html
> +               div:hover
Некорректный отступ

2017-10-15 18:02 UTC, msmirnov commented on tasks/19.html
> +                .global-scope div div
Здесь лучше использовать проверку на то, что элемент пустой

2017-10-15 18:02 UTC, msmirnov commented on tasks/2.html
> +	<!DOCTYPE html>
Зачем?

2017-10-15 18:02 UTC, msmirnov commented on tasks/2.html
> +				}
Здесь с отступами во всём блоке что-то странное произошло

2017-10-15 18:02 UTC, msmirnov commented on tasks/2.html
> +				div.c2
Почему c1 указан без div, а c2 вместе с div?

2017-10-15 18:02 UTC, msmirnov commented on tasks/4.html
> +				article article:nth-of-type(n+2)
Можно проще, если проверить что article стоит после article

2017-10-15 18:02 UTC, msmirnov commented on tasks/7.html
> +                article img:not([alt^='css'])
Здесь можно не указывать значение атрибута, а просто проверить его наличие

2017-10-15 18:02 UTC, msmirnov commented on tasks/9.html
> +                a[href*='ya.ru']:visited
Здесь тоже можно не проверять значение аттрибута

2017-10-16 17:22 UTC, HazipovVF commented on tasks/2.html
> +	<!DOCTYPE html>
Знал бы я откуда этот отступ
![image](https://user-images.githubusercontent.com/17403908/31625701-6b641104-b2c0-11e7-8a44-203e7cdb340c.png)

2017-10-16 17:33 UTC, HazipovVF commented on tasks/13.html
> +                div div:only-of-type
Делал для обращения к потомкам

2017-10-16 17:33 UTC, HazipovVF commented on tasks/16.html
> +                .global-results div.c2.c3.c4.c5.c6
Думал это будет слишком просто

2017-10-16 17:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 18:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 18:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 05:39 UTC, msmirnov requested changes

2017-10-17 05:39 UTC, msmirnov commented on tasks/3.html
> +                {
Лишний пробел

2017-10-17 05:39 UTC, msmirnov commented on tasks/3.html
> +                {
Лишний пробел

2017-10-17 06:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 07:19 UTC, msmirnov approved these changes

2017-10-17 07:20 UTC, closed without merging