v.1
urfu-2017/markup-task-2 pull request #54
Opened 2017-10-14 14:56 UTC by Naturin

2017-10-14 14:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 10:57 UTC, Mokoshka requested changes

2017-10-19 10:57 UTC, Mokoshka commented on tasks/11.html
> +                }
Если сделать пустой input, то он будет показываться как невалидный

2017-10-19 10:57 UTC, Mokoshka commented on tasks/12.html
> +                }
Эту задачу можно решить проще, использовав псевдокласс empty

2017-10-19 10:57 UTC, Mokoshka commented on tasks/13.html
> +                .global-scope :nth-child(5) :first-child
Здесь можно написать селектор проще, так же заиспользовав другой псевдокласс

2017-10-19 10:57 UTC, Mokoshka commented on tasks/18.html
> +                }
При наведении рядом с квадратиками срабатывает ховер. Такого быть не должно
![2017-10-19 15 49 50 2017-10-19 15-50-11](https://user-images.githubusercontent.com/14892550/31767622-37d47ba4-b4e5-11e7-98fd-91dcc331a4b7.png)

2017-10-19 10:57 UTC, Mokoshka commented on tasks/20.html
> +                .red-gt2 div:nth-last-child(n+3):first-child ~ div
А зачем first-child?

2017-10-19 10:57 UTC, Mokoshka commented on tasks/20.html
> +                .red-gt2 div:nth-last-child(n+3):first-child ~ div
Очень круто, когда код написан в едином стиле. Здесь ты в одной строчке используешь пробелы `(n + 3)`, а в другой нет `(n+3)`. Напиши в едином стиле. Я бы посоветовала написать без пробелов

2017-10-19 10:57 UTC, Mokoshka commented on tasks/4.html
> +                    border-top: none;
А зачем убирать здесь border?

2017-10-19 10:57 UTC, Mokoshka commented on tasks/9.html
> +                }
Если ссылка посещена, то hover не срабатывает

2017-10-19 11:00 UTC, Mokoshka commented on tasks/11.html
> +                }
Уточню, что пустой input не должен быть невалидным пока на нем не было фокуса

2017-10-22 08:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-22 13:13 UTC, Mokoshka requested changes
Поправишь hover и закрою задачу

2017-10-22 13:13 UTC, Mokoshka commented on tasks/9.html
> +                a:not([href]):not(:hover)
Почему not? По условию задачи псевдоссылка должна быть полупрозрачной при наведении же

2017-10-22 13:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-22 14:45 UTC, closed without merging