Александр Рогов
urfu-2017/markup-task-2 pull request #58
Opened 2017-10-14 17:26 UTC by San4eyZ

2017-10-14 17:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 17:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 17:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 17:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 07:57 UTC, evilj0e requested changes

2017-10-15 07:57 UTC, evilj0e commented on package.json
> +    "eslint": "^4.8.0"
Зачем тебе понадобился eslint в этой задаче?

2017-10-15 07:57 UTC, evilj0e commented on tasks/11.html
> +                .global-scope input:first-child
Завяжись на валидность / невалидность поля, а не какой это ребёнок.

2017-10-15 07:57 UTC, evilj0e commented on tasks/12.html
> +                    background: #ff6;
Читай внимательно задание, что нужно использовать

2017-10-15 07:57 UTC, evilj0e commented on tasks/12.html
> +                .global-scope div:nth-child(2n+1):not(:nth-child(5))
Напиши более простое правило.
Подсказка: как считаешь, перенос строки – это контент или нет?

2017-10-15 07:57 UTC, evilj0e commented on tasks/13.html
> +                .global-scope div:nth-child(4n+1) div:first-child
Ты жёстко завязался за порядок. Так делать не стоит. Поищи, может тебе что-то подойдёт из псевдоклассов?

2017-10-15 07:57 UTC, evilj0e commented on tasks/15.html
> +                a[href$='.zip']::after
Тебе нужно подсвечивать только те ссылки, что приводят к скачиванию архива, а не все, что ведут на архив

2017-10-15 07:57 UTC, evilj0e commented on tasks/17.html
> +                input:checked ~ input:checked
Можешь совместить эти оба правила, чтобы получилось одно?

2017-10-15 07:57 UTC, evilj0e commented on tasks/19.html
> +                .global-scope > div:first-child > div:last-child
Зачем тебе везде `>`?

2017-10-15 07:57 UTC, evilj0e commented on tasks/19.html
> +                .global-scope > div > div
Подумай про контент и примени псевдокласс.

2017-10-15 07:57 UTC, evilj0e commented on tasks/2.html
> +                    background: #ff6698;
Читай внимательно задание

2017-10-15 07:57 UTC, evilj0e commented on tasks/20.html
> +                .red-gt2 > div
Совмести два правила в одно и напиши короче.

2017-10-15 07:57 UTC, evilj0e commented on tasks/4.html
> +                .global-scope article:first-of-type
Совмести два правила в одно и напиши короче.

2017-10-15 07:57 UTC, evilj0e commented on tasks/5.html
> +                    background: #000;
Читай задание, что можно использовать

2017-10-15 07:57 UTC, evilj0e commented on tasks/6.html
> +                .global-scope a
Напиши все правила с привязкой к атрибуту ссылок

2017-10-15 07:57 UTC, evilj0e commented on tasks/8.html
> +                .global-scope a[target='_blank']
Таргет никак не связан с тем, ведут ли у тебя ссылки на внешний сайт или это относительные ресурсы

2017-10-15 07:57 UTC, evilj0e commented on tasks/9.html
> +                .global-scope .link:first-child:visited
Для чего везде используешь `:first-child`?

2017-10-15 07:57 UTC, evilj0e commented on tasks/9.html
> +                .global-scope .link:first-child:hover:not(:active) ~ .link
Можно написать проще

2017-10-15 08:34 UTC, evilj0e commented
🍅

2017-10-15 13:50 UTC, San4eyZ commented on package.json
> +    "eslint": "^4.8.0"
Это что-бы webstorm не ругался)) Ему зачем-то был нужен eslint

2017-10-15 15:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 15:52 UTC, San4eyZ commented
Добрый вечер. Не понял что не так во 2 и 12 заданиях в плане использования. С 19 и 20 нужна подсказка, я не смог придумать ничего лучше)

2017-10-16 05:44 UTC, evilj0e commented on tasks/19.html
> +                .global-scope > div > div
Существуют псевдоклассы `:empty` и `:not`.
В этом случае можно было бы применить что-то из этого.

2017-10-16 05:46 UTC, evilj0e commented
В 2 и 12, скорее всего я был строг и требовал слишком явного переопределения только фона. Переделывать не нужно.
В 19 можно воспользоваться псевдоклассом `:empty`, `:not`.

2017-10-16 05:46 UTC, closed without merging