Бочик Софья
urfu-2017/markup-task-2 pull request #61
Opened 2017-10-14 19:27 UTC by reindeermur

2017-10-14 19:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 19:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 19:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 10:36 UTC, dotokoto requested changes
Привет! Я проверила, оставила некоторое количество замечаний ) Когда поправишь, лучше напиши мне в Слак, чтобы я второй раз посмотрела

2017-10-16 10:36 UTC, Dotokoto commented on tasks/1.html
> +                    div
Можно объединить с верхним:
```
aside,
div {
 background: #6698ff;
}
```

2017-10-16 10:36 UTC, Dotokoto commented on tasks/2.html
> +                div:first-child
1) Здесь лучше выбрать по классам `.c1.c2`
2) Рамка возьмется из `.c1`, ее можно второй раз не определять

2017-10-16 10:36 UTC, Dotokoto commented on tasks/3.html
> +                    border: none;
Лучше писать селекторы так, чтобы в последующих пришлось сбрасывать как можно меньше правил.
Например, в первом селекторе выбрать по  `.global-scope > div`, чтобы добавить рамку только для внешних дивов

2017-10-16 10:36 UTC, Dotokoto commented on tasks/4.html
> +                article > article:nth-child(3)
Здесь можно обойтись одним селектором `article + article`. Этот селектор выберет для каждого article правого соседа и задаст ему рамку. А так как первый article ни для кого не будет правым соседом, у него рамка не появится

2017-10-16 10:36 UTC, Dotokoto commented on tasks/20.html
> +                div.red-gt2:nth-child(n+3) div
В данном примере этот селектор работает. Но по условию хочется выделять внутренние, когда их больше двух, независимо от расположения внешнего дива.
![css 2000 2017-10-16 15-30-10](https://user-images.githubusercontent.com/8973726/31607836-6ce3bc5c-b287-11e7-97d8-2baf5094c8a3.png)

2017-10-16 10:37 UTC, Dotokoto commented
:tomato:

2017-10-19 20:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 20:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 20:21 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 20:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 20:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 20:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 20:27 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 06:19 UTC, dotokoto approved these changes

2017-10-20 06:19 UTC, Dotokoto commented
Принято задание и доп задача 👍

2017-10-20 06:19 UTC, closed without merging