Копорушкин Данил
urfu-2017/markup-task-2 pull request #62
Opened 2017-10-14 19:28 UTC by darl0ck

2017-10-14 19:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 19:08 UTC, bazhenova requested changes
Привет) Первая стопка замечаний. Некоторые места нужно переделать полностью. Если что - пиши, помогу. А пока 🍅

2017-10-15 19:08 UTC, bazhenova commented on tasks/11.html
> +                [value*='invalid']
Давай все же будем указывать, к чему именно применяется это свойство. Поправь, пожалуйста, во всех местах

2017-10-15 19:08 UTC, bazhenova commented on tasks/3.html
> +                div > div
А нужен ли тут `>`?

2017-10-15 19:08 UTC, bazhenova commented on tasks/4.html
> +                    border-top: hidden ;
А зачем тут это свойство?

2017-10-15 19:08 UTC, bazhenova commented on tasks/5.html
> +                input[type='checkbox']:checked ~ div
Лучше вместо последнего `div` указать его класс. Вдруг у тебя в файле будет куча `div`-ов, но не ко всем нужно применить эти стили

2017-10-15 19:08 UTC, bazhenova commented on tasks/6.html
> +                [href='https://vk.ru']
Тут тоже укажи, к чему применяем выборку

2017-10-15 19:08 UTC, bazhenova commented on tasks/7.html
> +                div img[alt*='css']
Можно было попробовать инвертировать условие, тогда бы написал всего одно свойство вместо двух)

2017-10-15 19:08 UTC, bazhenova commented on tasks/8.html
> +                [target='_blank']
Тут ты прописал правило для ссылок, которые открываются в другом окне. А задача стоит:
>Выделите только ссылки на внешние относительно my-site.ru ресурсы

Перепиши, пожалуйста

2017-10-15 19:08 UTC, bazhenova commented on tasks/9.html
> +                .link[href*='ya']:hover
Проверь эту задачу еще разок. Не работает наведение на первую сслыку, а так же нажатие на обе. Подсказка: посмотри на специфичность)

2017-10-15 19:08 UTC, bazhenova commented on tasks/11.html
> +                [value*='invalid']:focus
Если фокусируюсь на инпуте с зеленым email, то инпут не становится синим. А должен

2017-10-15 19:08 UTC, bazhenova commented on tasks/12.html
> +                div:nth-child(2n+1)
Попробуй решить эту задачу без использования `nth-child` и `nth-of-type`

2017-10-15 19:08 UTC, bazhenova commented on tasks/14.html
> +                    content: '+';
Забыл про отступы
![image](https://user-images.githubusercontent.com/12410663/31587978-c8aaf222-b204-11e7-8e77-c22c23d78060.png)

2017-10-15 19:08 UTC, bazhenova commented on tasks/15.html
> +                    content: '↓' ;
Добавь отступов перед стрелочками
![image](https://user-images.githubusercontent.com/12410663/31587985-e60141b4-b204-11e7-9ea6-bec7e13d1271.png)

2017-10-15 19:08 UTC, bazhenova commented on tasks/16.html
> +                div:nth-child(2).c1
Давай немного упростим эту запись)

2017-10-15 19:08 UTC, bazhenova commented on tasks/16.html
> +                div:last-child
Раз используешь `!important`, чтобы перебить стили, то в данном случае можно написать просто класс

2017-10-15 19:08 UTC, bazhenova commented on tasks/18.html
> +                    opacity: .5;
Изначально цвет квадратиков должен быть темным. При наведении на конкретный квадратик он должен стать совсем ярким, а остальные более прозрачными. Надо переделать

2017-10-15 19:08 UTC, bazhenova commented on tasks/20.html
> +                /* stylelint-disable */
Было разрешено поправить конфиг и использовать id. Остальные правила должны соблюдаться. Переделай

2017-10-15 19:08 UTC, bazhenova commented on tasks/20.html
> +                    background: #ff6;
Что-то пошло не так с определением цвета
![image](https://user-images.githubusercontent.com/12410663/31588061-f89656b0-b205-11e7-9790-4ac783345047.png)

2017-10-16 06:06 UTC, darl0ck commented on tasks/11.html
> +                [value*='invalid']:focus
просто на картинке был только невалидный инпут синий 😢

2017-10-16 06:14 UTC, darl0ck commented on tasks/16.html
> +                div:last-child
Не получается он все перекрашивает

2017-10-16 06:33 UTC, darl0ck commented on tasks/20.html
> +                    background: #ff6;
прастити(((

2017-10-16 06:44 UTC, darl0ck commented on tasks/8.html
> +                [target='_blank']
просто тут все внешние ссылки открываются в новом окне 😄

2017-10-16 07:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 08:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 14:41 UTC, darl0ck commented on tasks/18.html
> +                    opacity: .5;
тоже переделал но что-то она не закрывается

2017-10-19 06:42 UTC, bazhenova reviewed
Уже намного лучше! Осталось еще чуть-чуть правок. Вперед) 🍅

2017-10-19 06:42 UTC, bazhenova commented on tasks/7.html
> +                    opacity: .5;
Судя по макету, это должно быть немного прозрачнее)

2017-10-19 06:42 UTC, bazhenova commented on tasks/11.html
> +                input[value*='email']:focus
В этой задаче достаточно написать просто `input:focus`

2017-10-19 06:42 UTC, bazhenova commented on tasks/13.html
> +                 div > div:first-child,
Давай в этой задаче тоже обойдемся без использования `*-child`. Подумай, что объединяет выделенные квадраты?

2017-10-19 06:42 UTC, bazhenova commented on tasks/16.html
> +                div.c1
А теперь вопрос: почему тут надо писать именно так и почему выше используешь `!important`?) Ничего править не надо, просто хочу услышать ответ

2017-10-19 06:42 UTC, bazhenova commented on tasks/17.html
> +                    outline: none !important;
Можно ли в этой задаче обойтись без использования `!important`?

2017-10-19 06:42 UTC, bazhenova commented on tasks/19.html
> +                div > div
В этой задаче можно использовать псевдокласс `:empty`. Ну это так, на будущее)

2017-10-19 06:42 UTC, bazhenova commented on tasks/20.html
> +
Странное добавление пустой строки в начало файла Оо

2017-10-19 06:42 UTC, bazhenova commented on tasks/20.html
> +                div:nth-child(n+3) > div
👍

2017-10-19 18:14 UTC, darl0ck commented on tasks/11.html
> +                input[value*='email']:focus
ну просто чтобы уточнить к чему

2017-10-19 18:31 UTC, darl0ck commented on tasks/13.html
> +                 div > div:first-child,
ой не знаю , не знаю 😢

2017-10-19 18:35 UTC, darl0ck commented on tasks/16.html
> +                div.c1
!important выше чтобы перебить то, что у нас в самом диве прописан стаил , а он выше ценится 
a div.c1 тоже чтобы он именно к с1 применил мой стаил

2017-10-19 18:41 UTC, darl0ck commented on tasks/17.html
> +                    outline: none !important;
Думаю что нельзя
Ибо нам же нужно перебить класс ,что выше ,а так как там мы еще и всех братков инпута к инпуту засовываем то импортант нужен

2017-10-19 18:42 UTC, darl0ck commented on tasks/19.html
> +                div > div
Хорошо 
Спасибо !

2017-10-19 18:42 UTC, darl0ck commented on tasks/20.html
> +
WebStorm - шалунишка

2017-10-19 18:42 UTC, darl0ck commented on tasks/20.html
> +                div:nth-child(n+3) > div
ееееее

2017-10-19 18:44 UTC, darl0ck commented on tasks/7.html
> +                    opacity: .5;
Вроде так

2017-10-19 18:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-19 18:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 18:49 UTC, darl0ck commented
Жду жду жду проверочки

2017-10-20 05:36 UTC, bazhenova reviewed
Есть 2 существенные правки: избавиться от `!important`, где я указала, а также чуть-чуть причесать код с использованием `:only-of-type`. И да, не забудь удалить лишние комментарии в коде) 🍅

2017-10-20 05:36 UTC, bazhenova commented on tasks/13.html
> +                /*article > div:first-child,*/
Лучше не оставлять после себя комментарии, не несущие смысловой нагрузки. Они только загрязняют код

2017-10-20 05:36 UTC, bazhenova commented on tasks/13.html
> +                 div > :not(aside)
Ты на правильном пути) Смотри, выделенные квадраты - это те, которые являются единственными `div` в своем блоке. Есть специальный псевдокласс `:only-of-type`, который как раз эту задачу и решает)

2017-10-20 05:36 UTC, bazhenova commented on tasks/16.html
> +                div.c1
Про `!important` верно. Про `div.c1` добавлю: в данной задаче надо написать именно так, а не просто `.c1`, чтобы добавить специфичности

2017-10-20 05:36 UTC, bazhenova commented on tasks/17.html
> +                    outline: none !important;
На самом деле можно) Использовать `!important` нужно, только если нет другого способа перебить стили. В данной задаче надо выделить все, которые не выбраны. Можно сделать вот такое правило:
`input[type='checkbox']:checked ~ input:not(:checked)`
То есть что хотим выбрать, то и выбираем)) Тогда правило с `!important` будет не нужно

2017-10-20 05:36 UTC, bazhenova commented on tasks/18.html
> +                    opacity: .5;
👍

2017-10-20 05:36 UTC, bazhenova commented on tasks/20.html
> +
Oo

2017-10-20 16:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 16:45 UTC, darl0ck commented
Жду жду жду яблочка

2017-10-20 17:05 UTC, bazhenova approved these changes

2017-10-20 17:06 UTC, bazhenova commented
Вот теперь всё выглядит хорошо) Молодец!

2017-10-20 17:06 UTC, closed without merging

2017-10-20 17:06 UTC, darl0ck commented
Юху