Бабич Людмила
urfu-2017/markup-task-2 pull request #63
Opened 2017-10-14 20:54 UTC by Ludmilishee

2017-10-14 20:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 21:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 21:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 21:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 07:55 UTC, vaseker commented
🍅
Нужно упростить селекторы – общее для всех задач требование. Если в задаче явно не указана ошибка, нужно все равно проанализировать решение на излишнюю сложность.

2017-10-15 07:55 UTC, vaseker requested changes
🍅

2017-10-15 07:55 UTC, vaseker commented on tasks/1.html
> +                    .global-scope div,
Не нужно делать по аналогии с дефолтными селекторами. Нужно делать по тем знаниям, что были выданы на лекциях. Тут повышение специфичности через указание .global-scope или чуть ниже через div не требуется.
Запрашиваю упрощение селекторов по всем задачам.

2017-10-15 07:55 UTC, vaseker commented on tasks/10.html
> +                .global-scope .title:first-letter
~~.global-scope~~

2017-10-15 07:55 UTC, vaseker commented on tasks/11.html
> +                input[type='email']:invalid
не нужно усложнять и конкретизировать "поле ввода __email__"

2017-10-15 07:55 UTC, vaseker commented on tasks/13.html
> +                .global-scope div:nth-child(4n+1) div:first-child
~~div~~

2017-10-15 07:55 UTC, vaseker commented on tasks/14.html
> +                    content: '+';
на макете есть отступ

2017-10-15 07:55 UTC, vaseker commented on tasks/14.html
> +                ul li:before
~~ul~~

2017-10-15 07:55 UTC, vaseker commented on tasks/15.html
> +                ul li a[href$='zip']:after
излишняя конкретизация

2017-10-15 07:55 UTC, vaseker commented on tasks/15.html
> +                    content: ' \2193';
тут есть отступ, а в 14 задаче нет

2017-10-15 07:55 UTC, vaseker commented on tasks/16.html
> +                body .global-scope > .c2.c3.c4.c5.c6
окей, у нас в линтере по ошибке нельзя пользоватья id. но не надо городить монстр-селектор.
```css
.c2 { background-color: #xxx !important; }
```

2017-10-15 07:55 UTC, vaseker commented on tasks/19.html
> +                .global-scope div:first-child div:last-child
куча лишних div и .global-scope

2017-10-15 08:47 UTC, vaseker commented on tasks/4.html
> +                .global-scope > article:not(:nth-of-type(1))
тут нужно обойтись простым `+` селектором

2017-10-15 08:49 UTC, vaseker commented on tasks/5.html
> +                input[type='checkbox']:checked ~ .tab
~~type~~

2017-10-20 20:05 UTC, Ludmilishee commented on tasks/16.html
> +                body .global-scope > .c2.c3.c4.c5.c6
@vaseker Здесь по-другому ведь не получится, т.к. нужно перебить inline-правило

2017-10-20 20:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-20 20:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-21 06:58 UTC, vaseker commented on tasks/16.html
> +                body .global-scope > .c2.c3.c4.c5.c6
тут я как раз рекомендую использовать !important

2017-10-21 07:03 UTC, vaseker approved these changes

2017-10-21 07:03 UTC, vaseker commented on tasks/1.html
> +                    div.c1
тут можно без `div`

2017-10-21 07:04 UTC, vaseker commented
🍏

2017-10-21 07:04 UTC, closed without merging