Свалов Дмитрий
urfu-2017/markup-task-2 pull request #64
Opened 2017-10-14 21:50 UTC by KrazyD

2017-10-14 21:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 21:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 14:36 UTC, Vittly commented on tasks/10.html
> +                p.description:first-line
p - лишнее кмк

2017-10-17 08:20 UTC, Vittly commented on tasks/2.html
> +                article div.c1.c2
почему не `div.c1.c2` ?

2017-10-17 08:29 UTC, Vittly requested changes
🍅 
давай править, некоторые задачи не решены правильно, по некоторым мелкие замечания

2017-10-17 08:29 UTC, Vittly commented on tasks/4.html
> +                article > article:not(:nth-of-type(1))
можно короче

2017-10-17 08:29 UTC, Vittly commented on tasks/6.html
> +                    color: red;
в задаче требуются другие цвета

2017-10-17 08:29 UTC, Vittly commented on tasks/8.html
> +                a[href*='//']:not([href*='//my-site.ru'])
есть более короткий признак

2017-10-17 08:29 UTC, Vittly commented on tasks/9.html
> +                }
ховер на вторую ссылку неверно обрабатывается, наведение на первую ссылку неверное. Давай эту задачу порешаем внимательнее

2017-10-17 08:29 UTC, Vittly commented on tasks/12.html
> +                }
есть более короткое решение, хинт - некоторые дивы пустые

2017-10-17 08:29 UTC, Vittly commented on tasks/13.html
> +                article > div:nth-of-type(4n+1) > :first-child
можно короче

2017-10-17 08:29 UTC, Vittly commented on tasks/14.html
> +                    content: '+';
тут и ниже пробела не хватает

2017-10-17 08:29 UTC, Vittly commented on tasks/16.html
> +                .global-result .global-scope .c1
можно добиться большей специфичности более коротким способом

2017-10-17 08:29 UTC, Vittly commented on tasks/17.html
> +                input[type='checkbox']:checked ~ input:not(:checked)
в одном месте написал тип, а в другом не стал - почему? Можно писать коротко

2017-10-17 08:29 UTC, Vittly commented on tasks/18.html
> +                }
при наведении остальные квадраты должны становиться бледнее - надо доделать задачу

2017-10-17 08:29 UTC, Vittly commented on tasks/20.html
> +                .red-gt2 :nth-last-child(3) ~ div
можно короче

2017-10-20 21:16 UTC, KrazyD commented on tasks/8.html
> +                a[href*='//']:not([href*='//my-site.ru'])
@Vittly Не могли бы Вы дать небольшую подсказку, какой признак? Ведь если имеется в виду target="_blank", то в таком виде могут быть оформлены любые ссылки. Признак rel="external" не выделит все необходимые ссылки, придется писать два селектора.

2017-10-20 21:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-20 21:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-21 14:24 UTC, Vittly requested changes
🍅 
еще немного

2017-10-21 14:24 UTC, Vittly commented on tasks/13.html
> +                div:nth-of-type(4n+1) > :first-child
погляди на one-of-type - мб подойдет?

2017-10-21 21:25 UTC, KrazyD commented on tasks/13.html
> +                div:nth-of-type(4n+1) > :first-child
Спасибо, only-of-type идеально подошел :)

2017-10-21 21:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 06:37 UTC, Vittly approved these changes

2017-10-23 06:37 UTC, Vittly commented
хорошо!

2017-10-23 06:37 UTC, closed without merging