Петрова Оля
urfu-2017/markup-task-2 pull request #65
Opened 2017-10-14 22:45 UTC by OlgaPetrova96

2017-10-14 22:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-14 23:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-14 23:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 18:17 UTC, msmirnov requested changes
🍅

2017-10-15 18:17 UTC, msmirnov commented on tasks/1.html
> +                    aside
Этот селектор можно объединить с предыдущим

2017-10-15 18:17 UTC, msmirnov commented on tasks/11.html
> +                input:required:hover
Нужно проверять не hover, а focus. И required тут не при чем.

2017-10-15 18:17 UTC, msmirnov commented on tasks/12.html
> +                }
В этом примере нужно проверять пуст ли элемент

2017-10-15 18:17 UTC, msmirnov commented on tasks/13.html
> +                div div:only-of-type
Зачем здесь два раза div?

2017-10-15 18:17 UTC, msmirnov commented on tasks/16.html
> +                }
В этом примере important должен остаться только в одном селекторе, его использовать нужно только в крайних случаях.

2017-10-15 18:17 UTC, msmirnov commented on tasks/17.html
> +                }
Работает некорректно: подсвечиваться должны только те чекбоксы, которые стоят после выбранного. Когда ни один не выбран, все должны быть неподсвеченными. И это всё можно сделать в одном селекторе.

2017-10-15 18:17 UTC, msmirnov commented on tasks/19.html
> +                div div
Здесь нужно проверить элемент на пустоту

2017-10-15 18:17 UTC, msmirnov commented on tasks/19.html
> +                div:nth-child(1) div:last-child
1 – это first

2017-10-15 18:17 UTC, msmirnov commented on tasks/19.html
> +                div:nth-child(4) div:first-child
4 – это last

2017-10-15 18:17 UTC, msmirnov commented on tasks/2.html
> +            div.c1.c2
Почему здесь div, а в других нет?

2017-10-15 18:17 UTC, msmirnov commented on tasks/3.html
> +            div
Из-за того, что здесь указан просто div, border переопределяется дважды на одном элементе. Это негативно сказывается на производительности.

2017-10-15 18:17 UTC, msmirnov commented on tasks/4.html
> +                article:nth-child(n+4)
Если добавим еще один пункт, то это перестанет работать. Здесь нужно задавать стили для всех article, которые стоят после article

2017-10-15 18:17 UTC, msmirnov commented on tasks/5.html
> +                }
Цвета лучше задавать в hex. Смущает дублирование правил в первом и третьем селекторе.

2017-10-15 18:17 UTC, msmirnov commented on tasks/6.html
> +                a:nth-child(n+2)
Здесь нужно завязываться на значение атрибута href

2017-10-15 18:17 UTC, msmirnov commented on tasks/7.html
> +                div:not(:nth-child(3n+1))
Нужно обратить внимание на существование атрибута alt

2017-10-15 18:17 UTC, msmirnov commented on tasks/8.html
> +                a[target='_blank']
> Выделите только ссылки на внешние относительно my-site.ru ресурсы

2017-10-15 18:17 UTC, msmirnov commented on tasks/9.html
> +                }
Во всём этом файле можно не проверять значение href, а только отслеживать его наличие

2017-10-15 19:36 UTC, OlgaPetrova96 commented on tasks/13.html
> +                div div:only-of-type
ой, это я сначала затупила и другим способом пыталась сделать, а потом исправила и про div второй забыла (не заметила, потому что и так заработало)

2017-10-15 19:37 UTC, OlgaPetrova96 commented on tasks/11.html
> +                input:required:hover
тут я просто невнимательно задание прочитала

2017-10-15 19:45 UTC, OlgaPetrova96 commented on tasks/2.html
> +            div.c1.c2
тут даже оправдаться нечем, бывают у меня тупые ошибочки (к сожалению, довольно часто, но я стараюсь :))

2017-10-15 22:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-15 22:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 04:16 UTC, msmirnov requested changes
🍅

2017-10-16 04:16 UTC, msmirnov commented on tasks/1.html
> +
Лишняя строка

2017-10-16 04:16 UTC, msmirnov commented on tasks/12.html
> +                }
Вместо двух селекторов с `:nth-child`, можно проверить на непустоту

2017-10-16 04:16 UTC, msmirnov commented on tasks/16.html
> +                div
Если определять для `div`, то тогда цвет будет переопределяться для всех элементов. В этом задании `!important` нужно использовать только для того, чтобы перебить специфичность атрибута `style`.

2017-10-16 04:16 UTC, msmirnov commented on tasks/16.html
> +                div.c1
Почему здесь `div`, а в других нет?

2017-10-16 04:16 UTC, msmirnov commented on tasks/17.html
> +                input[type='checkbox']:checked ~ input[type='checkbox']:not(:checked)
Почти ОК, только тут не нужно выбирать элементы по атрибуту, других инпутов на странице нет.

2017-10-16 04:16 UTC, msmirnov commented on tasks/6.html
> +                }
Цвет первой ссылки не по макету

2017-10-16 04:16 UTC, msmirnov commented on tasks/7.html
> +                img
Два раза определяешь прозрачность для одного элемента. Должен остаться один селектор, потому что 1 – значение по умолчанию.

2017-10-16 04:16 UTC, msmirnov commented on tasks/8.html
> +                a:not([href*='my-site.ru']):not([href^='/http'])
Проверять на `/http` странно, потому что там может стоять что угодно (например строка `abc`) и тогда код не будет работать

2017-10-16 18:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 18:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 18:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 05:46 UTC, msmirnov requested changes
🍅

2017-10-17 05:46 UTC, msmirnov commented on tasks/16.html
> +                }
Раньше было правильнее :) Я бы оставил div только в первом селекторе, а остальные сделал по классам и id. В данном задании нет смысла писать составные селекторы. Можно почитать про специфичность CSS селекторов.

2017-10-17 05:46 UTC, msmirnov commented on tasks/8.html
> +                a[href*='.com']
Я подставил адрес `https://w3c.org` и всё сломалось

2017-10-17 05:52 UTC, OlgaPetrova96 commented on tasks/16.html
> +                }
я читала про специфичность, но мозг отказывается воспринимать эту информацию :)

2017-10-17 05:53 UTC, OlgaPetrova96 commented on tasks/8.html
> +                a[href*='.com']
а если я .org, .net добавлю это нормально будет? или мне опять потом переделывать придется

2017-10-17 06:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 06:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 06:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 07:33 UTC, msmirnov commented
> Дико извиняюсь за это, но дедлайн близко...
Дэдлайн через неделю. Давай делать в первую очередь качественно.

2017-10-17 07:36 UTC, msmirnov requested changes
🍅

2017-10-17 07:36 UTC, msmirnov commented on tasks/16.html
> +                article .c1
А `article` зачем?

2017-10-17 07:36 UTC, msmirnov commented on tasks/8.html
> +                a[href*='.com']
Нет. У внешних ссылок другое общее есть: они начинаются с `//`, `http://` или `https://`

2017-10-17 12:46 UTC, OlgaPetrova96 commented on tasks/16.html
> +                article .c1
я специфичность так пыталась повысить и, как мне показалось, сработало

2017-10-17 12:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 18:42 UTC, msmirnov requested changes
Осталось чуть-чуть 🍅

2017-10-17 18:42 UTC, msmirnov commented on tasks/8.html
> +                }
А теперь все три нужно в один объединить и вообще красота будет, потому что три раза копировать одно правило не очень хорошо :)

2017-10-17 18:42 UTC, msmirnov commented on tasks/16.html
> +                article .c1
Кажется, что если убрать `article`, то ничего не изменится

2017-10-18 07:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-18 07:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-18 07:36 UTC, OlgaPetrova96 commented on tasks/16.html
> +                article .c1
Кажется, я пробовала без него

2017-10-18 07:36 UTC, OlgaPetrova96 commented on tasks/16.html
> +                article .c1
![image](https://user-images.githubusercontent.com/32207291/31705236-025bc8f2-b3fe-11e7-8681-cd6d36e7771b.png)
![image](https://user-images.githubusercontent.com/32207291/31705260-199bba68-b3fe-11e7-8ae0-fb892c498547.png)

2017-10-18 07:42 UTC, OlgaPetrova96 commented on tasks/8.html
> +                }
ой, я не туда написала. Ну ничего, повторю тут на всякий случай
Если убрать article, то всё сразу работать перестанет, я проверила 
![image](https://user-images.githubusercontent.com/32207291/31706225-99d915ce-b401-11e7-8e41-c32e0f1051aa.png)
![image](https://user-images.githubusercontent.com/32207291/31706250-bd803098-b401-11e7-8ed3-612f78624a81.png)

2017-10-19 06:40 UTC, msmirnov approved these changes

2017-10-19 06:41 UTC, closed without merging