Мифтахов Валерий
urfu-2017/markup-task-2 pull request #66
Opened 2017-10-14 23:30 UTC by WMiftakhov

2017-10-14 23:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 11:09 UTC, Mokoshka requested changes

2017-10-19 11:09 UTC, Mokoshka commented on tasks/1.html
> +                    aside
Свойства для селекторов aside и div совпадают, можно объединить

2017-10-19 11:09 UTC, Mokoshka commented on tasks/12.html
> +                }
Это выглядит как хак) Реши задачу, не изменяя html, только средствами css

2017-10-19 11:09 UTC, Mokoshka commented on tasks/13.html
> +                }
Аналогично, только css изменять

2017-10-19 11:09 UTC, Mokoshka commented on tasks/16.html
> +                }
И в этой задаче не надо изменять html

2017-10-19 11:09 UTC, Mokoshka commented on tasks/18.html
> +                }
Навожу рядом с квадратиками, происходит hover. Такого быть не должно
![2017-10-19 15 49 50 2017-10-19 16-04-39](https://user-images.githubusercontent.com/14892550/31768099-44422a60-b4e7-11e7-85e0-46037e0be8ad.png)

2017-10-19 11:09 UTC, Mokoshka commented on tasks/2.html
> +                .c3
И здесь тоже зак. Реши задачу, не изменяя html

2017-10-19 11:09 UTC, Mokoshka commented on tasks/3.html
> +                }
Не менять html

2017-10-19 11:09 UTC, Mokoshka commented on tasks/4.html
> +                }
Не менять html

2017-10-19 11:09 UTC, Mokoshka commented on tasks/6.html
> +                }
Не менять html

2017-10-19 11:09 UTC, Mokoshka commented on tasks/7.html
> +                }
Не менять html

2017-10-19 11:09 UTC, Mokoshka commented on tasks/9.html
> +                }
Не менять html

2017-10-20 15:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 15:43 UTC, WMiftakhov commented on tasks/18.html
> +                }
Добрый день. Исправил все задачи кроме 18-ой. Как сделать так, чтобы не только братья, следующие за элементом меняли свойства, но и предыдущие, я, к сожалению, не знаю. Натолкнете на мысль?

2017-10-22 13:29 UTC, Mokoshka requested changes

2017-10-22 13:29 UTC, Mokoshka commented on tasks/12.html
> +                div:nth-child(4n-1)
Эту задачу можно решить, не использую nth-child. Советую почитать про псевдоклассы и обратить внимание на :empty

2017-10-22 13:29 UTC, Mokoshka commented on tasks/13.html
> +                div:nth-child(4n-3) > div:first-child
Эту задачу тоже можно решить без nth-child, используя псевдоклассы

2017-10-22 13:29 UTC, Mokoshka commented on tasks/18.html
> +                }
Сделать можно, но для этого надо поиграться с margin и padding у элементов. Сделала замечание, до того, как узнала, что такое поведение приемлемо. Извиняюсь.
Исправлять не надо

2017-10-22 13:29 UTC, Mokoshka commented on tasks/4.html
> +                article:nth-child(n+4)
Здесь можно использовать селектор проще и универсальнее, чем nth-child

2017-10-22 13:29 UTC, Mokoshka commented on tasks/7.html
> +                }
Эту задачу можно решить, используя один селектор и не используя nth-child)

2017-10-22 13:29 UTC, Mokoshka commented on tasks/9.html
> +                }
link при наведении должен менять цвет на розовый, не изменяя прозрачность. Так же при клике на link он должен поменять цвет на зеленый

2017-10-23 13:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 13:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 13:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 13:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 13:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 13:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 13:57 UTC, Mokoshka requested changes
При наведении на посещенную ссылку, она все еще не меняет цвет на нужный
А еще изменены цвета остальных ссылок на странице 
![css 2000 2017-10-23 18-56-38](https://user-images.githubusercontent.com/14892550/31893088-05619d54-b824-11e7-9974-5a567cc45046.png)

2017-10-23 14:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 15:31 UTC, Mokoshka approved these changes

2017-10-23 15:31 UTC, closed without merging