Белёв Александр
urfu-2017/markup-task-2 pull request #67
Opened 2017-10-15 07:23 UTC by sanyabas

2017-10-15 07:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 18:17 UTC, mokhov requested changes
11 задание не решено:
<img width="170" alt="css 2000 2017-10-16 01-12-12" src="https://user-images.githubusercontent.com/357689/31587626-2b05beca-b20f-11e7-845d-fef4a9b187cb.png">

в 12 задании цвета немного другие (попробуй найти какой-нибудь плагин для браузера, который поможет определить цвет по наведению на него в браузере):
<img width="1001" alt="css 2000 2017-10-16 01-13-24" src="https://user-images.githubusercontent.com/357689/31587632-3e29ca00-b20f-11e7-95ef-023f26a45a66.png">

По остальным задачам мелкие замечания, которые тоже неплохо бы поправить

2017-10-15 18:17 UTC, mokhov commented on tasks/3.html
> +                div > div
Зачем нужен `>`?

2017-10-15 18:17 UTC, mokhov commented on tasks/9.html
> +                a[href]:visited
visited стили не должны переопределять стили при наведении и нажатии, иначе ссылка перестаёт реагировать на действия

2017-10-15 18:17 UTC, mokhov commented on tasks/9.html
> +                a:not([href]):hover
Не понял зачем здесь `:not([href])`

2017-10-15 18:17 UTC, mokhov commented on tasks/16.html
> +                    background: #f66 !important;
Можно ли эту задачу решить без `!important`?

2017-10-15 18:17 UTC, mokhov commented on tasks/17.html
> +                input:checked ~ input:not(:checked)
👍

2017-10-15 18:17 UTC, mokhov commented on tasks/18.html
> +                article:hover > div
И снова – зачем тебе `>`?

2017-10-15 18:17 UTC, mokhov commented on tasks/20.html
> +                div > div:first-child:nth-last-child(4) ~ div
А если элементов будет 5?

2017-10-15 18:24 UTC, mokhov commented
:tomato

2017-10-15 18:32 UTC, sanyabas commented on tasks/20.html
> +                div > div:first-child:nth-last-child(4) ~ div
Конечно, будет копипаста. Был ещё вариант покрасить внутренности последних двух `div`ов, но он показался мне более костыльным. Или всё же пойдёт?

2017-10-19 08:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 08:31 UTC, sanyabas commented
С цветом оказалось, что, когда правил замечания `stylelint`а вместо `#ff6` написал `#f66`

2017-10-19 08:32 UTC, sanyabas commented on tasks/16.html
> +                    background: #f66 !important;
А разве можно перебить inline стили без `!important`? Если да, то было бы здорово узнать, как

2017-10-19 17:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-21 07:41 UTC, mokhov commented
Молодец! 👍

2017-10-21 07:41 UTC, closed without merging