Левшин Миша
urfu-2017/markup-task-2 pull request #68
Opened 2017-10-15 08:50 UTC by LevshinMisha

2017-10-15 08:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-15 20:57 UTC, f0rmat1k requested changes

2017-10-15 20:57 UTC, f0rmat1k commented on tasks/2.html
> +                .global-scope > .c1
А зачем .global-scope в селекторах? Если можно решить задачу более коротким селектором, стоит так и делать.

2017-10-15 20:57 UTC, f0rmat1k commented on tasks/18.html
> +                .global-scope > div
Задача решена неверно. Обрати внимание на вид остальных квадратов при наведении на какой-либо.

2017-10-15 20:57 UTC, f0rmat1k commented on tasks/20.html
> +                .global-scope > div > div:first-child:nth-last-child(2)
Можно решить сильно более оптимально, но ок.

2017-10-15 21:47 UTC, LevshinMisha commented on tasks/18.html
> +                .global-scope > div
Действительно, не заметил. Исправил.

2017-10-15 21:52 UTC, LevshinMisha commented on tasks/2.html
> +                .global-scope > .c1
Я решил, что добавление .global-scope в селектор сделает этот селектор более конкретным.
Например в реальном проекте у нас вполне может быть класс .c1 в другом месте.
Это может привести к тому что верстка может рано или поздно неожиданно сломается.
Но если говорить о данном задании, то да здесь можно было написать и без .global-scope
Впрочем убрать не составит проблемы.

2017-10-15 21:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-15 22:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 07:44 UTC, f0rmat1k commented on tasks/2.html
> +                .global-scope > .c1
@LevshinMisha Над именно под задание делать. Если в реальном проекте у тебя такой селектор `.global-scope > .c1`, то это уже проигрыш. Как от каскада, так и от названия классов.

2017-10-16 07:45 UTC, closed without merging