Шаламова Лилия
urfu-2017/markup-task-2 pull request #71
Opened 2017-10-15 11:27 UTC by LiliyaShalamova

2017-10-15 11:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-15 12:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 10:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 19:28 UTC, Grimfrid commented on tasks/1.html
> +                    .global-scope :first-child,
Молодец! Но в этом задании не надо привязываться к порядку, используй селектор тега вместо них

2017-10-16 19:32 UTC, Grimfrid commented on tasks/2.html
> +                div:first-child
Тут нужно использовать только селектор класса

2017-10-16 19:35 UTC, Grimfrid commented on tasks/6.html
> +                a + a
Тут суть задания в том, что ссылка на vk должна быть синего цвета, а на яндекс красного. В твоем случае если поменять теги местами, то уже так не будет. Попробуй написать селектор использующий атрибут ссылки

2017-10-16 19:37 UTC, Grimfrid commented on tasks/7.html
> +                div:nth-child(2),
`:nth-child` в этом случае - плохо, посмотри чем разметка картинок отличается, надо это использовать

2017-10-16 19:39 UTC, Grimfrid commented on tasks/8.html
> +                a[target='_blank']
`target='_blank'` может использоваться и для открытия ссылок на тот же ресурс, по-этому тут надо использовать `href`

2017-10-16 19:42 UTC, Grimfrid commented on tasks/9.html
> +                {
Попробуй это задание сделать лучше:
1) Использовать `.link`
2) Не использовать `url` в стилях, тут достаточно наличия `href`
3) Написать стили не используя `!important`
4) Не используя соседние селекторы

Если будут вопросы почему и как, пиши в слак или задавай тут

2017-10-16 19:47 UTC, Grimfrid commented on tasks/20.html
> +                .red-gt2 :nth-last-child(n + 3):first-child
`:first-child` кажется лишнее,  и фон дублируется

2017-10-16 19:47 UTC, Grimfrid requested changes
🍅

2017-10-16 21:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 17:18 UTC, Grimfrid commented on tasks/2.html
> +                .c1:not(.c2)
Тут можно обойтись без `:not` если поменять стили местами, то есть (`.c1.c2`) перенести в конец. Попробуй, очень важно понимать как порядок влияет на результат

2017-10-17 17:21 UTC, Grimfrid requested changes
Все очень круто! Давай только разберемся с порядком во втором задании, будут вопросы - пиши, там в идеале должно получиться 3 селектора

🍅

2017-10-17 18:27 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-18 21:17 UTC, Grimfrid commented
🍏

2017-10-19 07:33 UTC, closed without merging