Мелкозёров Леонид Олегович
urfu-2017/markup-task-2 pull request #72
Opened 2017-10-15 11:54 UTC by danmerus

2017-10-15 11:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-15 12:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-29 22:26 UTC, v3new requested changes
Необходимо как минимум исправить задачи с томатом 🍅

2017-10-29 22:26 UTC, v3new commented on tasks/10.html
> +                article p:first-child:first-letter
Почему просто не обратился к классу `.title`?
И повышение специфичности при помощи `article` в любом случае излишне

2017-10-29 22:26 UTC, v3new commented on tasks/12.html
> +                    background: #f66;
Цвет должен быть: `#ff6`

2017-10-29 22:26 UTC, v3new commented on tasks/12.html
> +                div:nth-of-type(2n+1):not(:nth-of-type(5))
За находчивость +, но советую обратить внимание на псевдокласс `:empty`

2017-10-29 22:26 UTC, v3new commented on tasks/13.html
> +                div:nth-of-type(4n+1) > div
Неплохо, но почитай про `:only-of-type`

2017-10-29 22:26 UTC, v3new commented on tasks/14.html
> +                    font-weight: bold;
На выполнение не влияет, но должно быть `font-weight: normal;`

2017-10-29 22:26 UTC, v3new commented on tasks/16.html
> +               div#id1
Тут вполне и без `div` можно обойтись

2017-10-29 22:26 UTC, v3new commented on tasks/18.html
> +                div
Код работает некорректно, если какой-либо квадрат выделен, остальные должны становиться более прозрачными 🍅

2017-10-29 22:26 UTC, v3new commented on tasks/20.html
> +                div > div:first-child:nth-last-child(n+3),
👍

2017-10-29 22:26 UTC, v3new commented on tasks/4.html
> +                article:not(:nth-of-type(1))
Обрати внимание на селектор `+`

2017-10-29 22:26 UTC, v3new commented on tasks/9.html
> +                [href]
Задача решена неверно - ссылки при нажатии не меняют состояние 🍅

2017-10-29 22:26 UTC, v3new commented
Я поздно приступил к проверке задания, попрошу, чтобы за это не снижали балл

2017-10-29 22:30 UTC, v3new commented
Удали, пожалуйста, коммит с файлами не в том месте

2017-10-30 05:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-30 05:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-04 08:56 UTC, danmerus commented
не подскажете можно ли на сайте как то коммит удалить или только через гит?

2017-11-08 08:24 UTC, Dotokoto commented on tasks/2.html
> +                .c1
Здесь можно было решить проще, использовав селекторы `.c1`, `.c2`, `.c1.c2`

2017-11-08 08:24 UTC, Dotokoto commented on tasks/7.html
> +                div:nth-child(3)
Здесь можно было использовать `img:not([alt])`

2017-11-08 08:24 UTC, Dotokoto commented on tasks/9.html
> +                [href]:active
Изменение цвета по наведению все еще не работает, так как оно переопределяется стилями по hover (надо было просто `:active` стили унести ниже ховера в файле, чтобы они переопределили цвет)

2017-11-08 08:24 UTC, Dotokoto commented on 10.html
> +                article p:nth-of-type(2):first-line
Можно было использовать классы `.title` и `.description`, тогда селекторы получились бы проще

2017-11-08 08:25 UTC, closed without merging