Королев Лев
urfu-2017/markup-task-2 pull request #81
Opened 2017-10-15 18:11 UTC by rkrk117

2017-10-15 18:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 13:56 UTC, bazhenova requested changes
Привет! Есть несколько замечаний, их нужно поправить. В остальном все норм) Пока 🍅

2017-10-19 13:56 UTC, bazhenova commented on tasks/1.html
> +                    [id]
Ничего себе ты тут магию написал)) Давай все-таки не будем так делать в этой задаче. Вам разрешили использовать `#id`, для этого нужно поправить правила для линтера. Но можно обойтись и без использования id ;)

2017-10-19 13:56 UTC, bazhenova commented on tasks/6.html
> +                a:first-of-type
Это, конечно, удобно применять правила к первой ссылке, но все сломается, если поменять их местами. Сделай выборку по-другому

2017-10-19 13:56 UTC, bazhenova commented on tasks/9.html
> +                .link[href]:active
При нажатии на вторую ссылку, она не становится яркой

2017-10-19 13:56 UTC, bazhenova commented on tasks/11.html
> +                    border: 3px solid #6698ff;
Input должен становиться синим при фокусе, а не при наведении. Фокус - это когда "находишься в нем", нажал на него. То же самое должно происходить при фокусе на втором инпуте. Переделай, пожалуйста. 

А еще давай будем указывать к чему применяем правила, то есть в данном случае будет `input[value^='invalid']`

2017-10-19 13:56 UTC, bazhenova commented on tasks/13.html
> +                div > div:first-child:only-of-type
Для чего `:first-child`?

2017-10-19 13:56 UTC, bazhenova commented on tasks/16.html
> +                    background: #ff6698 !important;
Использовать `!important` нужно только тогда, когда необходимо перебить другие стили, но другого способа для этого нет. В этой задаче можно написать стили так, чтобы не использовать `!important` везде. Хочу это увидеть)

2017-10-19 13:56 UTC, bazhenova commented on tasks/18.html
> +                    opacity: .5;
При наведении на одну из плиток остальные должны стать бледнее. Сейчас происходит только увеличение яркости у наведенной плитки. Надо доделать задачу

2017-10-19 13:56 UTC, bazhenova commented on tasks/20.html
> +                .red-gt2 div:nth-last-child(n+3)
👍

2017-10-22 15:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-22 15:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 06:37 UTC, bazhenova reviewed
Осталась пара замечаний. Надо поправить, потом закрою) 🍅

2017-10-23 06:37 UTC, bazhenova commented on tasks/16.html
> +                article.global-scope div.c2.c3.c4.c5.c6
А точно ли надо указывать столько классов?

2017-10-23 06:37 UTC, bazhenova commented on tasks/16.html
> +                article.global-scope div.c2.c3.c4.c5.c6
Когда указываешь классы, то можно обойтись без указания тега, так как это необходимо только в том случае, если нужно повысить специфичность

2017-10-23 10:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 10:39 UTC, bazhenova approved these changes

2017-10-23 10:40 UTC, bazhenova commented
Вот теперь выглядит все норм. Молодец!

2017-10-23 10:40 UTC, closed without merging