imlemented
urfu-2017/markup-task-2 pull request #86
Opened 2017-10-15 20:54 UTC by iriskis

2017-10-15 20:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 07:22 UTC, msmirnov requested changes
🍅

2017-10-17 07:22 UTC, msmirnov commented on tasks/10.html
> +                p.title::first-letter
Зачем здесь указывать параграф?

2017-10-17 07:22 UTC, msmirnov commented on tasks/13.html
> +                div > div:only-of-type
Зачем составной селектор?

2017-10-17 07:22 UTC, msmirnov commented on tasks/16.html
> +                }
Почему в этом задании в селекторах указываем div? Что будет, если мы их уберем?

2017-10-17 07:22 UTC, msmirnov commented on tasks/8.html
> +                a[href*='//']:not([href*='my-site'])
Ссылка на внешний ресурс может начинаться не только со `//`

2017-10-17 15:54 UTC, iriskis commented on tasks/16.html
> +                }
Некоторые можно убрать, но нужно оставить div для псевдокласса :empty (такой синтаксис) и для div.c1, чтобы увеличить специфичность селектора, иначе этот div попадет под правило селектора div:empty

2017-10-17 16:14 UTC, iriskis commented on tasks/8.html
> +                a[href*='//']:not([href*='my-site'])
Исправила

2017-10-17 16:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 18:51 UTC, msmirnov reviewed
🍅

2017-10-17 18:51 UTC, msmirnov commented on tasks/16.html
> +                }
Да, обойти это можно сделав не `:empty`, а `:first-child`

2017-10-17 18:51 UTC, msmirnov commented on tasks/8.html
> +                [target='_blank']
Не самый лучший признак внешней ссылки. Попробуй внешнюю отличать по признаку (`//`, `http://` или `https://`)

2017-10-17 19:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 19:37 UTC, iriskis commented on tasks/16.html
> +                }
Хм, здесь ведь подвох, да?:D не применяется .c1, из-за того, что в файлике global.css прописан такой селектор .global-scope_16 div и у меня не остается выбора, как увеличить специфичность своего селектора

2017-10-18 04:26 UTC, msmirnov approved these changes

2017-10-18 04:26 UTC, closed without merging