done tasks
urfu-2017/markup-task-2 pull request #89
Opened 2017-10-16 09:08 UTC by HEXBATAET

2017-10-16 09:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 09:12 UTC, HEXBATAET commented
Можно ли в 18 задаче добиться красоты решения?)

2017-10-18 07:47 UTC, mokhov requested changes
4 задание решено не до конца (нужно чуть-чуть внимательнее). В 11 задании типичная ошибка заключается в том, что я не могу узнать что ввёл что-то верно, пока не уберу фокус

2017-10-18 07:47 UTC, mokhov commented on tasks/1.html
> +                div.c1
Зачем здесь нужен селектор тега?

2017-10-18 07:47 UTC, mokhov commented on tasks/9.html
> +            a[href]
Нужен ли здесь `[href]`?

2017-10-18 07:47 UTC, mokhov commented
🍅

2017-10-18 08:22 UTC, HEXBATAET commented on tasks/9.html
> +            a[href]
Конкретно в 16 строке - да, ведь мы хотим поменять поведение только первой ссылки, и только у неё есть [href]. Можно опустить [href] в 16, но тогда добавить правило .link {color: black}. Это имелось в виду?

2017-10-18 08:23 UTC, HEXBATAET commented on tasks/1.html
> +                div.c1
Можно опустить.

2017-10-18 08:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-21 07:42 UTC, mokhov commented
Молодец 👍

2017-10-21 07:42 UTC, closed without merging