Катцин Валерий
urfu-2017/markup-task-2 pull request #90
Opened 2017-10-16 10:55 UTC by valerin5

2017-10-16 10:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 18:18 UTC, savichev-igor requested changes
:tomato:

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/11.html
> +                article input:focus
`article` можно убрать

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/12.html
> +                div
Сложно слишком сделал задание

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/13.html
> +                div > div:first-child:only-of-type
Из этого даже можно собрать лаконичное простое решение, попробуй)

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/14.html
> +                    list-style-type: none;
А это зачем)?

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/14.html
> +                    content: '+';
Пробел бы добавил

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/15.html
> +                a[href$='.zip']::after
А если в адресе будет содержаться `.zip`?

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/17.html
> +                :checked ~ input
Я бы лучше псевдокласс применял всегда к какому-нибудь другому селектору

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/19.html
> +                div:first-child > div:nth-child(4n)
Почему здесь не использовать `last-child`?

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/3.html
> +                :empty
Аналогично, я бы псевдокласс применял к чему-то более конкретному

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/19.html
> +                div:nth-child(5n-3) > div:nth-child(2n)
Сложные формулы очень

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/2.html
> +                div
В этом задании можно вообще обойтись без селектора тэгов

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/4.html
> +                article article
Задание не соответствует макету

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/5.html
> +                input:checked ~ div
Я бы не полагался на дефолтные стили в случае анчекед состояния

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/6.html
> +                a
Слишком широкая выборка

2017-10-16 18:18 UTC, Savichev-Igor commented on tasks/7.html
> +                article :not(:nth-child(3n+1))
Очень сложно

2017-10-17 08:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 08:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 08:47 UTC, valerin5 commented on tasks/15.html
> +                a[href$='.zip']::after
так ссылка на скачивание всегда кончается именем файла и его расширением, или нет?

2017-10-17 08:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 08:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 09:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 09:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 09:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 09:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 10:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 10:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 10:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 10:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 11:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 11:35 UTC, savichev-igor requested changes
Ещё чуть-чуть осталось

:tomato:

2017-10-17 11:35 UTC, Savichev-Igor commented on tasks/1.html
> +                        background: #6698ff;
Почему не объединишь этот стиль с `aside`?

2017-10-17 11:35 UTC, Savichev-Igor commented on tasks/1.html
> +                    div.c1
Выборку по тэгу здесь можно опустить

2017-10-17 11:35 UTC, Savichev-Igor commented on tasks/13.html
> +                div > div:only-of-type
`div >` можно опустить

2017-10-17 11:35 UTC, Savichev-Igor commented on tasks/16.html
> +                div.c1
Можно использовать селектор класса со вложенностью, вместо тэга и класса

2017-10-17 11:35 UTC, Savichev-Igor commented on tasks/16.html
> +                div.c7
Селектор тэга здесь ни к чему

2017-10-17 11:35 UTC, Savichev-Igor commented on tasks/17.html
> +                input:checked ~ input
Можно решить задание более изящно за один стиль

2017-10-17 11:35 UTC, Savichev-Igor commented on tasks/4.html
> +                article > article:not(:first-of-type)
Можно решить с использованием всего лишь двух тэгов `article`

2017-10-17 11:35 UTC, Savichev-Igor commented on tasks/5.html
> +                input:not(:checked) ~ div
`:not(:checked)` ни к чему

2017-10-17 11:35 UTC, Savichev-Igor commented on tasks/6.html
> +                a[href]
Уж лучше выбрать конкретно `yandex`, чем с помощью отрицания подсвечивать `vk`

2017-10-17 11:35 UTC, Savichev-Igor commented on tasks/7.html
> +                article :not(:last-child):not(:first-child)
Чрезвычайно сложно

2017-10-17 11:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 12:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 12:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 12:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 12:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 12:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 12:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 12:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-18 05:40 UTC, savichev-igor approved these changes

2017-10-18 05:40 UTC, Savichev-Igor commented on tasks/16.html
> +                :first-child:empty
Я бы всегда лучше применял псевдоклассы к каким-то тэгам или классам а не просто в воздух

2017-10-18 05:40 UTC, Savichev-Igor commented on tasks/7.html
> +                img:not([alt*='css'])
Можно просто `img:not(alt)`

2017-10-18 05:40 UTC, closed without merging