Done.
urfu-2017/markup-task-2 pull request #91
Opened 2017-10-16 16:09 UTC by denexapp

task 20 is solved too

2017-10-16 16:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 16:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 07:15 UTC, evilj0e requested changes
🍅

2017-10-17 07:15 UTC, evilj0e commented on tasks/1.html
> +                    aside
Стиль div и aside отличается?
Можно объединить

2017-10-17 07:15 UTC, evilj0e commented on tasks/15.html
> +                a[href$='.zip']::after
Ссылки на скачивание определяются дополнительным атрибутом `download`

2017-10-17 07:15 UTC, evilj0e commented on tasks/18.html
> +                :hover > div
Можно было более явно указать что `hover`

2017-10-17 07:15 UTC, evilj0e commented on tasks/20.html
> +                /* no google was used */
комментарий 🔥

2017-10-17 07:15 UTC, evilj0e commented on tasks/6.html
> +                /* assuming that vk.ru shouldn't be visited */
Раскрась в зависимости от значения атрибута `href`

2017-10-17 07:15 UTC, evilj0e commented on tasks/8.html
> +                a[target='_blank']
`target` не отвечает за то на какой ресурс ведёт ссылка.
Подумай как можно реализовать лучше.

2017-10-18 16:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-24 06:57 UTC, evilj0e approved these changes

2017-10-24 06:58 UTC, evilj0e commented
⭐️

2017-10-24 06:58 UTC, closed without merging