Гаранин Дмитрий
urfu-2017/markup-task-2 pull request #94
Opened 2017-10-16 19:53 UTC by DmitryGaranin

2017-10-16 19:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 16:00 UTC, bazhenova requested changes
Привет! Есть несколько замечаний, в паре мест надо переделать. В остальном все хорошо. Пока ставлю 🍅

2017-10-19 16:00 UTC, bazhenova commented on tasks/2.html
> +                .global-scope :first-child
Хорошо, что ты разобрался с `*-child`. А можно ли решить эту задачу без них?

2017-10-19 16:00 UTC, bazhenova commented on tasks/3.html
> +                .global-scope > div > div
А можно ли написать это правило чуть проще?

2017-10-19 16:00 UTC, bazhenova commented on tasks/7.html
> +                    opacity: .9;
А зачем тут это правило?

2017-10-19 16:00 UTC, bazhenova commented on tasks/8.html
> +                .global-scope a[target='_blank']
Ты выбрал все, которые открываются в новой вкладке. А задача стоит в выборе всех внешних ссылок по отношению к сайту. Надо переделать

2017-10-19 16:00 UTC, bazhenova commented on tasks/9.html
> +                .link:visited:active
Когда нажимаю на вторую ссылку, она не становится яркой

2017-10-19 16:00 UTC, bazhenova commented on tasks/11.html
> +                .global-scope :first-child:hover
Так. Давай уточним задание. Фокус - это когда ты фокусируешься на элементе, например, нажимаешь на него. У тебя сделано наведение. Такое же поведение должно быть и у второго инпута - он должен становиться синим при фокусе. Надо переделать

2017-10-19 16:00 UTC, bazhenova commented on tasks/12.html
> +                .global-scope div:nth-child(2n+1)
Давай попробуем решить эту задачу без использования 'nth-child'. Подумай, что объединяет блоки одинакового цвета

2017-10-19 16:00 UTC, bazhenova commented on tasks/15.html
> +                    content: '\2193';
Еще про отступы забыл
![image](https://user-images.githubusercontent.com/12410663/31780696-e557fccc-b50f-11e7-85d7-b67f98e7a221.png)

2017-10-19 16:00 UTC, bazhenova commented on tasks/20.html
> +                .global-scope div div:first-child:nth-last-child(4) ~ div
Ух, как много `*-child`. Молодец, что решил эту задачку, но давай попробуем решить эту задачу намного проще))

2017-10-22 10:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-22 10:06 UTC, DmitryGaranin commented on tasks/7.html
> +                    opacity: .9;
На примере эти картинки чуть тусклее, чем могли бы быть) 
даже сейчас
даже после указания, что это немного не так)

2017-10-23 06:10 UTC, bazhenova reviewed
Осталось последнее замечание. Поправь во всех файликах, и я закрою) 🍅

2017-10-23 06:10 UTC, bazhenova commented on tasks/11.html
> +                .global-scope :first-child
К чему относится `:first-child`? Лучше не писать псевдоклассы без указания к чему они относятся

2017-10-23 06:10 UTC, bazhenova commented on tasks/11.html
> +                .global-scope :last-child
То же самое по поводу `:last-child`

2017-10-23 06:10 UTC, bazhenova commented on tasks/16.html
> +                .global-scope :first-child
`:first-child`

2017-10-23 06:10 UTC, bazhenova commented on tasks/19.html
> +                .global-scope :first-child :last-child
`:first-child`, `:last-child`

2017-10-23 06:10 UTC, bazhenova commented on tasks/19.html
> +                .global-scope :first-child :last-child
В общем, поправь во всех местах

2017-10-23 06:10 UTC, bazhenova commented on tasks/20.html
> +                .global-scope div:nth-child(n+3) > div
👍

2017-10-23 15:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-23 16:59 UTC, bazhenova approved these changes
Вот теперь все выглядит хорошо. Одно замечание осталось, но я надеюсь, ты его учтешь в будущем. Молодец) 🍏

2017-10-23 16:59 UTC, bazhenova commented on tasks/19.html
> +                .global-scope :nth-child(2) :nth-child(2n)
Такое же замечание к `:nth-child`. Непонятно, к чему оно относится

2017-10-23 17:00 UTC, closed without merging