Project
urfu-2017/markup-task-2 pull request #95
Opened 2017-10-16 20:13 UTC by strota

2017-10-16 20:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:33 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:33 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 20:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:09 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 21:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 08:13 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 08:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 08:23 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 08:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 08:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 08:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 09:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 09:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 09:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 11:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 11:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 11:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 11:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-18 08:14 UTC, f0rmat1k requested changes

2017-10-18 08:14 UTC, f0rmat1k commented on 1.html
> +                    div.c1
Не стоит использовать более специфичные селекторы, чем требуется для решения. В данном случае достаточен более короткий.

2017-10-18 08:14 UTC, f0rmat1k commented on 9.html
> +                a:first-child:hover
Не работает наведение у посещенных ссылок.

2017-10-18 08:14 UTC, f0rmat1k commented on tasks/11.html
> +                article input:first-child:focus
Почему фокус только для первого инпута?

2017-10-18 08:14 UTC, f0rmat1k commented on tasks/18.html
> +                div
Упустила поведение остальных блоков при наведении. Обрати на них внимание.

2017-10-21 21:33 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-21 21:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-22 07:58 UTC, closed without merging