Плисковский Михаил
urfu-2017/markup-task-2 pull request #96
Opened 2017-10-16 20:59 UTC by snoward

2017-10-16 21:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 21:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 09:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-20 06:37 UTC, dotokoto requested changes
Привет! Я посмотрела, оставила замечания. Когда поправишь, напиши мне пожалуйста в Слак, чтобы я посмотрела правки.

2017-10-20 06:37 UTC, Dotokoto commented on tasks/1.html
> +                    aside
Этот селектор можно было объединить с первым, так как правила внутри одинаковые:
```
div,
aside {
...
}
```

2017-10-20 06:37 UTC, Dotokoto commented on tasks/2.html
> +                .c1:not(.c2)
Можно определить этот фон по селектору `.c1`. А селектор `.c1.c2` уже переопределит его для третьего дива

2017-10-20 06:37 UTC, Dotokoto commented on tasks/6.html
> +                a:visited
Здесь нельзя матчится на `visited`, так как этот параметр у каждого пользователя в каждом браузере разный. Попробуй смотреть на наличие домена  `yandex.ru` в ссылке

2017-10-20 06:37 UTC, Dotokoto commented on tasks/8.html
> +                [target='_blank']
Здесь в задании просят подсветить внешние относительно `my-site.ru` ресурсы, нужно тоже смотреть на атрибут `href` у ссылок

2017-10-20 06:37 UTC, Dotokoto commented on tasks/9.html
> +                a:not([href]):hover
`pseudolink` при нажатии должен переставать быть полупрозрачным, а сейчас он остается прозрачным

2017-10-20 06:37 UTC, Dotokoto commented on tasks/11.html
> +                input:invalid:hover
1) focus и hover это разные действия селекторы
2) синим при фокусе должен становится любой инпут, а не только invalid

2017-10-20 06:37 UTC, Dotokoto commented on tasks/18.html
> +                div:hover
Работает не совсем правильно. При наведении на один квадрат он должен стать ярким, а остальные должны становиться более прозрачными

2017-10-20 06:37 UTC, Dotokoto commented on tasks/20.html
> +                .red-gt2:nth-child(n + 3) div
Работает не так, как описано в задании. Надо красить именно те, где внутри больше двух элементов. А не просто элементы в двух последних дивах
![css 2000 2017-10-16 16-59-39](https://user-images.githubusercontent.com/8973726/31808038-c85cc910-b571-11e7-915c-ed125c575aa5.png)

2017-10-21 17:17 UTC, snoward commented on tasks/9.html
> +                a:not([href]):hover
✔

2017-10-21 17:17 UTC, snoward commented on tasks/8.html
> +                [target='_blank']
✔

2017-10-21 17:17 UTC, snoward commented on tasks/6.html
> +                a:visited
✔

2017-10-21 17:17 UTC, snoward commented on tasks/2.html
> +                .c1:not(.c2)
✔

2017-10-21 17:17 UTC, snoward commented on tasks/1.html
> +                    aside
✔

2017-10-21 17:20 UTC, snoward commented on tasks/11.html
> +                input:invalid:hover
✔

2017-10-21 17:26 UTC, snoward commented on tasks/18.html
> +                div:hover
✔

2017-10-21 17:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-21 17:51 UTC, snoward commented on tasks/20.html
> +                .red-gt2:nth-child(n + 3) div
✔

2017-10-21 17:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-22 06:27 UTC, dotokoto approved these changes

2017-10-22 06:27 UTC, closed without merging