Сафиуллин Рамиль
urfu-2017/markup-task-2 pull request #97
Opened 2017-10-16 21:02 UTC by Safic1996

2017-10-16 21:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 10:57 UTC, vaseker commented on tasks/14.html
> +                ul li::before
тут `ul` не нужен

2017-10-17 11:06 UTC, vaseker requested changes
🍅 
Нужны правки. 20е задание совсем мимо.

2017-10-17 11:06 UTC, vaseker commented on tasks/14.html
> +                    content: '+';
тут не хватает отступа

2017-10-17 11:06 UTC, vaseker commented on tasks/15.html
> +                    content: ' ↓ ';
тут многовато отступов

2017-10-17 11:06 UTC, vaseker commented on tasks/16.html
> +                div[class='c1']
`div.c1`

2017-10-17 11:06 UTC, vaseker commented on tasks/18.html
> +                    opacity: .1;
нечестно, но сойдет
![hovr](https://user-images.githubusercontent.com/1942271/31661459-3bfaa876-b354-11e7-808c-46856422f48f.png)

2017-10-17 11:06 UTC, vaseker commented on tasks/2.html
> +                .c2:nth-of-type(1)
тут надо продемонстрировать умение строить селекторы из классов и их комбинаций (без псевдо), с пониманием порядка написания правил.

2017-10-17 11:06 UTC, vaseker commented on tasks/20.html
> +                    background-color: #ff6698;
:goberserk: 
Читерство. Решена задача "выделите детей для .red-gt2 №3 и последний". 
Целевая задача не будет выполнена, если, например в первых .red-gt2 будет более 3х детей. Также все закрасится в .red-gt2 дальше 3, несмотря на количество детей.
> Выделите все внутренние элементы там, где их больше 2

Так неверно
<img width="232" alt="2017-10-15 12 57 41" src="https://user-images.githubusercontent.com/1942271/31582876-892d6f1e-b1a8-11e7-8f3c-821d70644b21.png">

Так норм
![20](https://user-images.githubusercontent.com/1942271/31582877-943ed276-b1a8-11e7-8312-127cc7245980.png)

2017-10-17 11:06 UTC, vaseker commented on tasks/9.html
> +                .global-result a[href]
тут ни к чему повышать специфичность через .global-result

2017-10-17 18:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-17 18:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 06:54 UTC, vaseker approved these changes
🍏 
Принимаю с одним замечанием.

2017-10-19 06:54 UTC, vaseker commented on tasks/11.html
> +                {
В этой задаче не нужно (да и вообще, кроме экзотических случаев) строить селектор  по значению.  Задача решается перечислением цветов для состояний  valid, invalid, focus в правильном порядке

2017-10-19 06:55 UTC, vaseker commented
🍏

2017-10-19 06:55 UTC, closed without merging

2017-10-19 07:16 UTC, Safic1996 commented on tasks/11.html
> +                {
Понял, учту в дальнейшем