Сделал все задания
urfu-2017/markup-task-2 pull request #98
Opened 2017-10-16 21:17 UTC by meta1-heart

2017-10-16 21:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 14:15 UTC, Vittly requested changes

2017-10-17 14:15 UTC, Vittly commented on tasks/1.html
> +                        background: rgb(100, 150, 255);
цвета надо из постановки задачи использовать в формате `#abcdef`

2017-10-17 14:15 UTC, Vittly commented on tasks/1.html
> +                        background: rgb(100, 150, 255);
везде надо поправить

🍅

2017-10-17 14:29 UTC, Vittly commented on tasks/11.html
> +                input[value='invalid-email']:focus
почитай про псевдоклассы valid/invalid

2017-10-17 14:30 UTC, Vittly commented on tasks/2.html
> +                div:not(:nth-child(3n))
есть более короткий способ

2017-10-17 14:30 UTC, Vittly commented on tasks/20.html
> +                .red-gt2 div:nth-last-child(n+3) ~ div
можно короче

2017-10-17 17:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-19 08:51 UTC, Vittly commented on tasks/4.html
> +                article ~ article
а можно было не тильду?

2017-10-19 09:02 UTC, Vittly commented
Гуд!

2017-10-19 09:02 UTC, closed without merging

2017-10-19 09:37 UTC, meta1-heart commented on tasks/4.html
> +                article ~ article
Использовать article:not(:first-of-type)?