Антон Фрешер
urfu-2017/markup-task-2 pull request #99
Opened 2017-10-16 22:37 UTC by tonyfresher

2017-10-16 22:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 22:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-10-16 22:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-16 23:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 07:31 UTC, msmirnov requested changes
Глобальное замечание: ты использовал очень тяжелые селекторы, из-за этого решение стало нечитаемым. Сделай, пожалуйста, так, чтобы селекторы были компактнее с текущей функциональностью.
🍅

2017-10-17 07:31 UTC, msmirnov commented on tasks/17.html
> +                }
Ожидается, что на выбранном селекте не будет рамки выделения
![image](https://user-images.githubusercontent.com/2646531/31651868-7770d784-b347-11e7-9eff-b369de4b3dd6.png)

2017-10-17 07:31 UTC, msmirnov commented on tasks/16.html
> +                article.global-scope > div#id1.c2.c3.c4.c5.c6
Весь селектор можно заменить на `#id1`

2017-10-17 16:48 UTC, tonyfresher commented on tasks/16.html
> +                article.global-scope > div#id1.c2.c3.c4.c5.c6
принято, сделано
учел, что айдишник уникален

2017-10-17 16:48 UTC, tonyfresher commented on tasks/17.html
> +                }
принято, поправлено

2017-10-17 16:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-17 16:53 UTC, tonyfresher commented
Про глобальное замечание: поясни, пожалуйста, что значит тяжелый селектор? Разве указывать article.global-scope здесь плохо? Или ты про что-то еще?

2017-10-17 18:59 UTC, msmirnov commented
В большинстве примеров можно обойтись без указания article.global-scope. Я не могу сказать, что указывать их плохо, но здесь это избыточно. В реальном коде мы не используем такие сложные селекторы, а стараемся делать более уникальные имена классов. Дело в том, что составные селекторы повышают [специфичность](https://habrahabr.ru/sandbox/47910/) и их становится сложнее переопределить.

2017-10-17 20:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-10-18 04:27 UTC, msmirnov approved these changes

2017-10-18 04:27 UTC, closed without merging